// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// Section: imports

// Section: boilerplate

// Section: functions

// This file is a placeholder for the auto-generated flutter_rust_bridge
// bindings. The actual file is generated during the build process by running:
//   flutter_rust_bridge_codegen generate
