//! # OxiCloud Core
//!
//! Cross-platform sync engine for OxiCloud, providing:
//! - WebDAV client for server communication
//! - File system watching for local changes
//! - SQLite database for sync state
//! - Conflict detection and resolution
//!
//! This crate is designed to be used via FFI from Flutter/Dart.

pub mod api;
pub mod domain;
pub mod application;
pub mod infrastructure;
mod frb_generated; /* auto-generated by flutter_rust_bridge */

// Re-export commonly used types
pub use domain::entities::{SyncItem, SyncStatus, SyncDirection, ConflictResolution};
pub use domain::ports::{SyncPort, StoragePort, AuthPort, FileWatcherPort};
pub use application::sync_service::SyncService;
pub use application::auth_service::AuthService;
