// Allow flutter_rust_bridge macro cfg checks
#![allow(unexpected_cfgs)]

//! # OxiCloud Core
//!
//! Cross-platform sync engine for OxiCloud, providing:
//! - WebDAV client for server communication
//! - File system watching for local changes
//! - SQLite database for sync state
//! - Conflict detection and resolution
//!
//! This crate is designed to be used via FFI from Flutter/Dart.

pub mod api;
pub mod application;
pub mod domain;
mod frb_generated;
pub mod infrastructure; /* auto-generated by flutter_rust_bridge */

// Re-export commonly used types
pub use application::auth_service::AuthService;
pub use application::sync_service::SyncService;
pub use domain::entities::{ConflictResolution, SyncDirection, SyncItem, SyncStatus};
pub use domain::ports::{AuthPort, FileWatcherPort, StoragePort, SyncPort};
