// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/oxicloud.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'domain/entities/auth.dart';
import 'domain/entities/config.dart';
import 'domain/entities/sync_item.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  DateTime dco_decode_Chrono_Utc(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  AuthResult dco_decode_auth_result(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  DateTime dco_decode_box_autoadd_Chrono_Utc(dynamic raw);

  @protected
  ConflictInfo dco_decode_box_autoadd_conflict_info(dynamic raw);

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

  @protected
  ServerInfo dco_decode_box_autoadd_server_info(dynamic raw);

  @protected
  SyncConfig dco_decode_box_autoadd_sync_config(dynamic raw);

  @protected
  ConflictInfo dco_decode_conflict_info(dynamic raw);

  @protected
  ConflictResolution dco_decode_conflict_resolution(dynamic raw);

  @protected
  ConflictType dco_decode_conflict_type(dynamic raw);

  @protected
  double dco_decode_f_32(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  List<RemoteFolder> dco_decode_list_remote_folder(dynamic raw);

  @protected
  List<SyncConflict> dco_decode_list_sync_conflict(dynamic raw);

  @protected
  List<SyncHistoryEntry> dco_decode_list_sync_history_entry(dynamic raw);

  @protected
  List<SyncItem> dco_decode_list_sync_item(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  DateTime? dco_decode_opt_box_autoadd_Chrono_Utc(dynamic raw);

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

  @protected
  ServerInfo? dco_decode_opt_box_autoadd_server_info(dynamic raw);

  @protected
  RemoteFolder dco_decode_remote_folder(dynamic raw);

  @protected
  ServerInfo dco_decode_server_info(dynamic raw);

  @protected
  SyncConfig dco_decode_sync_config(dynamic raw);

  @protected
  SyncConflict dco_decode_sync_conflict(dynamic raw);

  @protected
  SyncDirection dco_decode_sync_direction(dynamic raw);

  @protected
  SyncHistoryEntry dco_decode_sync_history_entry(dynamic raw);

  @protected
  SyncItem dco_decode_sync_item(dynamic raw);

  @protected
  SyncResult dco_decode_sync_result(dynamic raw);

  @protected
  SyncStatus dco_decode_sync_status(dynamic raw);

  @protected
  SyncStatusInfo dco_decode_sync_status_info(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  DateTime sse_decode_Chrono_Utc(SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  AuthResult sse_decode_auth_result(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  DateTime sse_decode_box_autoadd_Chrono_Utc(SseDeserializer deserializer);

  @protected
  ConflictInfo sse_decode_box_autoadd_conflict_info(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  ServerInfo sse_decode_box_autoadd_server_info(SseDeserializer deserializer);

  @protected
  SyncConfig sse_decode_box_autoadd_sync_config(SseDeserializer deserializer);

  @protected
  ConflictInfo sse_decode_conflict_info(SseDeserializer deserializer);

  @protected
  ConflictResolution sse_decode_conflict_resolution(SseDeserializer deserializer);

  @protected
  ConflictType sse_decode_conflict_type(SseDeserializer deserializer);

  @protected
  double sse_decode_f_32(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  List<RemoteFolder> sse_decode_list_remote_folder(SseDeserializer deserializer);

  @protected
  List<SyncConflict> sse_decode_list_sync_conflict(SseDeserializer deserializer);

  @protected
  List<SyncHistoryEntry> sse_decode_list_sync_history_entry(SseDeserializer deserializer);

  @protected
  List<SyncItem> sse_decode_list_sync_item(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  DateTime? sse_decode_opt_box_autoadd_Chrono_Utc(SseDeserializer deserializer);

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

  @protected
  ServerInfo? sse_decode_opt_box_autoadd_server_info(SseDeserializer deserializer);

  @protected
  RemoteFolder sse_decode_remote_folder(SseDeserializer deserializer);

  @protected
  ServerInfo sse_decode_server_info(SseDeserializer deserializer);

  @protected
  SyncConfig sse_decode_sync_config(SseDeserializer deserializer);

  @protected
  SyncConflict sse_decode_sync_conflict(SseDeserializer deserializer);

  @protected
  SyncDirection sse_decode_sync_direction(SseDeserializer deserializer);

  @protected
  SyncHistoryEntry sse_decode_sync_history_entry(SseDeserializer deserializer);

  @protected
  SyncItem sse_decode_sync_item(SseDeserializer deserializer);

  @protected
  SyncResult sse_decode_sync_result(SseDeserializer deserializer);

  @protected
  SyncStatus sse_decode_sync_status(SseDeserializer deserializer);

  @protected
  SyncStatusInfo sse_decode_sync_status_info(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  int cst_encode_Chrono_Utc(DateTime raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_i_64(raw.microsecondsSinceEpoch);
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_String(String raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_list_prim_u_8_strict(utf8.encoder.convert(raw));
  }

  @protected
  ffi.Pointer<ffi.Int64> cst_encode_box_autoadd_Chrono_Utc(DateTime raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return wire.cst_new_box_autoadd_Chrono_Utc(cst_encode_Chrono_Utc(raw));
  }

  @protected
  ffi.Pointer<wire_cst_conflict_info> cst_encode_box_autoadd_conflict_info(ConflictInfo raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ptr = wire.cst_new_box_autoadd_conflict_info();
    cst_api_fill_to_wire_conflict_info(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<ffi.Int64> cst_encode_box_autoadd_i_64(PlatformInt64 raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return wire.cst_new_box_autoadd_i_64(cst_encode_i_64(raw));
  }

  @protected
  ffi.Pointer<wire_cst_server_info> cst_encode_box_autoadd_server_info(ServerInfo raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ptr = wire.cst_new_box_autoadd_server_info();
    cst_api_fill_to_wire_server_info(raw, ptr.ref);
    return ptr;
  }

  @protected
  ffi.Pointer<wire_cst_sync_config> cst_encode_box_autoadd_sync_config(SyncConfig raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ptr = wire.cst_new_box_autoadd_sync_config();
    cst_api_fill_to_wire_sync_config(raw, ptr.ref);
    return ptr;
  }

  @protected
  int cst_encode_i_64(PlatformInt64 raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.toInt();
  }

  @protected
  ffi.Pointer<wire_cst_list_String> cst_encode_list_String(List<String> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_String(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      ans.ref.ptr[i] = cst_encode_String(raw[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_list_prim_u_8_strict(Uint8List raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_prim_u_8_strict(raw.length);
    ans.ref.ptr.asTypedList(raw.length).setAll(0, raw);
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_remote_folder> cst_encode_list_remote_folder(List<RemoteFolder> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_remote_folder(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      cst_api_fill_to_wire_remote_folder(raw[i], ans.ref.ptr[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_sync_conflict> cst_encode_list_sync_conflict(List<SyncConflict> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_sync_conflict(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      cst_api_fill_to_wire_sync_conflict(raw[i], ans.ref.ptr[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_sync_history_entry> cst_encode_list_sync_history_entry(
      List<SyncHistoryEntry> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_sync_history_entry(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      cst_api_fill_to_wire_sync_history_entry(raw[i], ans.ref.ptr[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_sync_item> cst_encode_list_sync_item(List<SyncItem> raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    final ans = wire.cst_new_list_sync_item(raw.length);
    for (var i = 0; i < raw.length; ++i) {
      cst_api_fill_to_wire_sync_item(raw[i], ans.ref.ptr[i]);
    }
    return ans;
  }

  @protected
  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_encode_opt_String(String? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? ffi.nullptr : cst_encode_String(raw);
  }

  @protected
  ffi.Pointer<ffi.Int64> cst_encode_opt_box_autoadd_Chrono_Utc(DateTime? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? ffi.nullptr : cst_encode_box_autoadd_Chrono_Utc(raw);
  }

  @protected
  ffi.Pointer<ffi.Int64> cst_encode_opt_box_autoadd_i_64(PlatformInt64? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? ffi.nullptr : cst_encode_box_autoadd_i_64(raw);
  }

  @protected
  ffi.Pointer<wire_cst_server_info> cst_encode_opt_box_autoadd_server_info(ServerInfo? raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw == null ? ffi.nullptr : cst_encode_box_autoadd_server_info(raw);
  }

  @protected
  int cst_encode_u_64(BigInt raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw.toSigned(64).toInt();
  }

  @protected
  void cst_api_fill_to_wire_auth_result(AuthResult apiObj, wire_cst_auth_result wireObj) {
    wireObj.success = cst_encode_bool(apiObj.success);
    wireObj.user_id = cst_encode_String(apiObj.userId);
    wireObj.username = cst_encode_String(apiObj.username);
    cst_api_fill_to_wire_server_info(apiObj.serverInfo, wireObj.server_info);
    wireObj.access_token = cst_encode_String(apiObj.accessToken);
  }

  @protected
  void cst_api_fill_to_wire_box_autoadd_conflict_info(
      ConflictInfo apiObj, ffi.Pointer<wire_cst_conflict_info> wireObj) {
    cst_api_fill_to_wire_conflict_info(apiObj, wireObj.ref);
  }

  @protected
  void cst_api_fill_to_wire_box_autoadd_server_info(
      ServerInfo apiObj, ffi.Pointer<wire_cst_server_info> wireObj) {
    cst_api_fill_to_wire_server_info(apiObj, wireObj.ref);
  }

  @protected
  void cst_api_fill_to_wire_box_autoadd_sync_config(
      SyncConfig apiObj, ffi.Pointer<wire_cst_sync_config> wireObj) {
    cst_api_fill_to_wire_sync_config(apiObj, wireObj.ref);
  }

  @protected
  void cst_api_fill_to_wire_conflict_info(ConflictInfo apiObj, wire_cst_conflict_info wireObj) {
    wireObj.conflict_type = cst_encode_conflict_type(apiObj.conflictType);
    wireObj.detected_at = cst_encode_Chrono_Utc(apiObj.detectedAt);
  }

  @protected
  void cst_api_fill_to_wire_remote_folder(RemoteFolder apiObj, wire_cst_remote_folder wireObj) {
    wireObj.id = cst_encode_String(apiObj.id);
    wireObj.name = cst_encode_String(apiObj.name);
    wireObj.path = cst_encode_String(apiObj.path);
    wireObj.size_bytes = cst_encode_u_64(apiObj.sizeBytes);
    wireObj.item_count = cst_encode_u_32(apiObj.itemCount);
    wireObj.is_selected = cst_encode_bool(apiObj.isSelected);
  }

  @protected
  void cst_api_fill_to_wire_server_info(ServerInfo apiObj, wire_cst_server_info wireObj) {
    wireObj.url = cst_encode_String(apiObj.url);
    wireObj.version = cst_encode_String(apiObj.version);
    wireObj.name = cst_encode_String(apiObj.name);
    wireObj.webdav_url = cst_encode_String(apiObj.webdavUrl);
    wireObj.quota_total = cst_encode_u_64(apiObj.quotaTotal);
    wireObj.quota_used = cst_encode_u_64(apiObj.quotaUsed);
    wireObj.supports_delta_sync = cst_encode_bool(apiObj.supportsDeltaSync);
    wireObj.supports_chunked_upload = cst_encode_bool(apiObj.supportsChunkedUpload);
  }

  @protected
  void cst_api_fill_to_wire_sync_config(SyncConfig apiObj, wire_cst_sync_config wireObj) {
    wireObj.sync_folder = cst_encode_String(apiObj.syncFolder);
    wireObj.database_path = cst_encode_String(apiObj.databasePath);
    wireObj.sync_interval_seconds = cst_encode_u_32(apiObj.syncIntervalSeconds);
    wireObj.max_upload_speed_kbps = cst_encode_u_32(apiObj.maxUploadSpeedKbps);
    wireObj.max_download_speed_kbps = cst_encode_u_32(apiObj.maxDownloadSpeedKbps);
    wireObj.delta_sync_enabled = cst_encode_bool(apiObj.deltaSyncEnabled);
    wireObj.delta_sync_min_size = cst_encode_u_64(apiObj.deltaSyncMinSize);
    wireObj.pause_on_metered = cst_encode_bool(apiObj.pauseOnMetered);
    wireObj.wifi_only = cst_encode_bool(apiObj.wifiOnly);
    wireObj.watch_filesystem = cst_encode_bool(apiObj.watchFilesystem);
    wireObj.ignore_patterns = cst_encode_list_String(apiObj.ignorePatterns);
    wireObj.notifications_enabled = cst_encode_bool(apiObj.notificationsEnabled);
    wireObj.launch_at_startup = cst_encode_bool(apiObj.launchAtStartup);
    wireObj.minimize_to_tray = cst_encode_bool(apiObj.minimizeToTray);
  }

  @protected
  void cst_api_fill_to_wire_sync_conflict(SyncConflict apiObj, wire_cst_sync_conflict wireObj) {
    wireObj.id = cst_encode_String(apiObj.id);
    wireObj.item_path = cst_encode_String(apiObj.itemPath);
    wireObj.local_modified = cst_encode_i_64(apiObj.localModified);
    wireObj.remote_modified = cst_encode_i_64(apiObj.remoteModified);
    wireObj.local_size = cst_encode_u_64(apiObj.localSize);
    wireObj.remote_size = cst_encode_u_64(apiObj.remoteSize);
    wireObj.conflict_type = cst_encode_conflict_type(apiObj.conflictType);
  }

  @protected
  void cst_api_fill_to_wire_sync_history_entry(
      SyncHistoryEntry apiObj, wire_cst_sync_history_entry wireObj) {
    wireObj.id = cst_encode_String(apiObj.id);
    wireObj.timestamp = cst_encode_i_64(apiObj.timestamp);
    wireObj.operation = cst_encode_String(apiObj.operation);
    wireObj.item_path = cst_encode_String(apiObj.itemPath);
    wireObj.direction = cst_encode_String(apiObj.direction);
    wireObj.status = cst_encode_String(apiObj.status);
    wireObj.error_message = cst_encode_opt_String(apiObj.errorMessage);
  }

  @protected
  void cst_api_fill_to_wire_sync_item(SyncItem apiObj, wire_cst_sync_item wireObj) {
    wireObj.id = cst_encode_String(apiObj.id);
    wireObj.path = cst_encode_String(apiObj.path);
    wireObj.name = cst_encode_String(apiObj.name);
    wireObj.is_directory = cst_encode_bool(apiObj.isDirectory);
    wireObj.size = cst_encode_u_64(apiObj.size);
    wireObj.content_hash = cst_encode_opt_String(apiObj.contentHash);
    wireObj.local_modified = cst_encode_opt_box_autoadd_Chrono_Utc(apiObj.localModified);
    wireObj.remote_modified = cst_encode_opt_box_autoadd_Chrono_Utc(apiObj.remoteModified);
    cst_api_fill_to_wire_sync_status(apiObj.status, wireObj.status);
    wireObj.direction = cst_encode_sync_direction(apiObj.direction);
    wireObj.etag = cst_encode_opt_String(apiObj.etag);
    wireObj.mime_type = cst_encode_opt_String(apiObj.mimeType);
  }

  @protected
  void cst_api_fill_to_wire_sync_result(SyncResult apiObj, wire_cst_sync_result wireObj) {
    wireObj.success = cst_encode_bool(apiObj.success);
    wireObj.items_uploaded = cst_encode_u_32(apiObj.itemsUploaded);
    wireObj.items_downloaded = cst_encode_u_32(apiObj.itemsDownloaded);
    wireObj.items_deleted = cst_encode_u_32(apiObj.itemsDeleted);
    wireObj.conflicts = cst_encode_u_32(apiObj.conflicts);
    wireObj.errors = cst_encode_list_String(apiObj.errors);
    wireObj.duration_ms = cst_encode_u_64(apiObj.durationMs);
  }

  @protected
  void cst_api_fill_to_wire_sync_status(SyncStatus apiObj, wire_cst_sync_status wireObj) {
    if (apiObj is SyncStatus_Synced) {
      wireObj.tag = 0;
      return;
    }
    if (apiObj is SyncStatus_Pending) {
      wireObj.tag = 1;
      return;
    }
    if (apiObj is SyncStatus_Syncing) {
      wireObj.tag = 2;
      return;
    }
    if (apiObj is SyncStatus_Conflict) {
      var pre_field0 = cst_encode_box_autoadd_conflict_info(apiObj.field0);
      wireObj.tag = 3;
      wireObj.kind.Conflict.field0 = pre_field0;
      return;
    }
    if (apiObj is SyncStatus_Error) {
      var pre_field0 = cst_encode_String(apiObj.field0);
      wireObj.tag = 4;
      wireObj.kind.Error.field0 = pre_field0;
      return;
    }
    if (apiObj is SyncStatus_Ignored) {
      wireObj.tag = 5;
      return;
    }
  }

  @protected
  void cst_api_fill_to_wire_sync_status_info(
      SyncStatusInfo apiObj, wire_cst_sync_status_info wireObj) {
    wireObj.is_syncing = cst_encode_bool(apiObj.isSyncing);
    wireObj.current_operation = cst_encode_opt_String(apiObj.currentOperation);
    wireObj.progress_percent = cst_encode_f_32(apiObj.progressPercent);
    wireObj.items_synced = cst_encode_u_32(apiObj.itemsSynced);
    wireObj.items_total = cst_encode_u_32(apiObj.itemsTotal);
    wireObj.last_sync_time = cst_encode_opt_box_autoadd_i_64(apiObj.lastSyncTime);
    wireObj.next_sync_time = cst_encode_opt_box_autoadd_i_64(apiObj.nextSyncTime);
  }

  @protected
  bool cst_encode_bool(bool raw);

  @protected
  int cst_encode_conflict_resolution(ConflictResolution raw);

  @protected
  int cst_encode_conflict_type(ConflictType raw);

  @protected
  double cst_encode_f_32(double raw);

  @protected
  int cst_encode_i_32(int raw);

  @protected
  int cst_encode_sync_direction(SyncDirection raw);

  @protected
  int cst_encode_u_32(int raw);

  @protected
  int cst_encode_u_8(int raw);

  @protected
  void cst_encode_unit(void raw);

  @protected
  void sse_encode_Chrono_Utc(DateTime self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_auth_result(AuthResult self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_Chrono_Utc(DateTime self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_conflict_info(ConflictInfo self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_server_info(ServerInfo self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_sync_config(SyncConfig self, SseSerializer serializer);

  @protected
  void sse_encode_conflict_info(ConflictInfo self, SseSerializer serializer);

  @protected
  void sse_encode_conflict_resolution(ConflictResolution self, SseSerializer serializer);

  @protected
  void sse_encode_conflict_type(ConflictType self, SseSerializer serializer);

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_list_remote_folder(List<RemoteFolder> self, SseSerializer serializer);

  @protected
  void sse_encode_list_sync_conflict(List<SyncConflict> self, SseSerializer serializer);

  @protected
  void sse_encode_list_sync_history_entry(List<SyncHistoryEntry> self, SseSerializer serializer);

  @protected
  void sse_encode_list_sync_item(List<SyncItem> self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_Chrono_Utc(DateTime? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_i_64(PlatformInt64? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_server_info(ServerInfo? self, SseSerializer serializer);

  @protected
  void sse_encode_remote_folder(RemoteFolder self, SseSerializer serializer);

  @protected
  void sse_encode_server_info(ServerInfo self, SseSerializer serializer);

  @protected
  void sse_encode_sync_config(SyncConfig self, SseSerializer serializer);

  @protected
  void sse_encode_sync_conflict(SyncConflict self, SseSerializer serializer);

  @protected
  void sse_encode_sync_direction(SyncDirection self, SseSerializer serializer);

  @protected
  void sse_encode_sync_history_entry(SyncHistoryEntry self, SseSerializer serializer);

  @protected
  void sse_encode_sync_item(SyncItem self, SseSerializer serializer);

  @protected
  void sse_encode_sync_result(SyncResult self, SseSerializer serializer);

  @protected
  void sse_encode_sync_status(SyncStatus self, SseSerializer serializer);

  @protected
  void sse_encode_sync_status_info(SyncStatusInfo self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

// ignore_for_file: camel_case_types, non_constant_identifier_names, avoid_positional_boolean_parameters, annotate_overrides, constant_identifier_names
// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import

/// generated by flutter_rust_bridge
class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary) : _lookup = dynamicLibrary.lookup;

  /// The symbols are looked up with [lookup].
  RustLibWire.fromLookup(
    ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName) lookup,
  ) : _lookup = lookup;

  void store_dart_post_cobject(DartPostCObjectFnType ptr) {
    return _store_dart_post_cobject(ptr);
  }

  late final _store_dart_post_cobjectPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(DartPostCObjectFnType)>>(
    'store_dart_post_cobject',
  );
  late final _store_dart_post_cobject =
      _store_dart_post_cobjectPtr.asFunction<void Function(DartPostCObjectFnType)>();

  void wire__crate__api__oxicloud__get_config(int port_) {
    return _wire__crate__api__oxicloud__get_config(port_);
  }

  late final _wire__crate__api__oxicloud__get_configPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
    'frbgen_oxicloud_app_wire__crate__api__oxicloud__get_config',
  );
  late final _wire__crate__api__oxicloud__get_config =
      _wire__crate__api__oxicloud__get_configPtr.asFunction<void Function(int)>();

  void wire__crate__api__oxicloud__get_conflicts(int port_) {
    return _wire__crate__api__oxicloud__get_conflicts(port_);
  }

  late final _wire__crate__api__oxicloud__get_conflictsPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
    'frbgen_oxicloud_app_wire__crate__api__oxicloud__get_conflicts',
  );
  late final _wire__crate__api__oxicloud__get_conflicts =
      _wire__crate__api__oxicloud__get_conflictsPtr.asFunction<void Function(int)>();

  void wire__crate__api__oxicloud__get_pending_items(int port_) {
    return _wire__crate__api__oxicloud__get_pending_items(port_);
  }

  late final _wire__crate__api__oxicloud__get_pending_itemsPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
    'frbgen_oxicloud_app_wire__crate__api__oxicloud__get_pending_items',
  );
  late final _wire__crate__api__oxicloud__get_pending_items =
      _wire__crate__api__oxicloud__get_pending_itemsPtr.asFunction<void Function(int)>();

  void wire__crate__api__oxicloud__get_remote_folders(int port_) {
    return _wire__crate__api__oxicloud__get_remote_folders(port_);
  }

  late final _wire__crate__api__oxicloud__get_remote_foldersPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
    'frbgen_oxicloud_app_wire__crate__api__oxicloud__get_remote_folders',
  );
  late final _wire__crate__api__oxicloud__get_remote_folders =
      _wire__crate__api__oxicloud__get_remote_foldersPtr.asFunction<void Function(int)>();

  void wire__crate__api__oxicloud__get_server_info(int port_) {
    return _wire__crate__api__oxicloud__get_server_info(port_);
  }

  late final _wire__crate__api__oxicloud__get_server_infoPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
    'frbgen_oxicloud_app_wire__crate__api__oxicloud__get_server_info',
  );
  late final _wire__crate__api__oxicloud__get_server_info =
      _wire__crate__api__oxicloud__get_server_infoPtr.asFunction<void Function(int)>();

  void wire__crate__api__oxicloud__get_sync_folders(int port_) {
    return _wire__crate__api__oxicloud__get_sync_folders(port_);
  }

  late final _wire__crate__api__oxicloud__get_sync_foldersPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
    'frbgen_oxicloud_app_wire__crate__api__oxicloud__get_sync_folders',
  );
  late final _wire__crate__api__oxicloud__get_sync_folders =
      _wire__crate__api__oxicloud__get_sync_foldersPtr.asFunction<void Function(int)>();

  void wire__crate__api__oxicloud__get_sync_history(int port_, int limit) {
    return _wire__crate__api__oxicloud__get_sync_history(port_, limit);
  }

  late final _wire__crate__api__oxicloud__get_sync_historyPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.Uint32)>>(
    'frbgen_oxicloud_app_wire__crate__api__oxicloud__get_sync_history',
  );
  late final _wire__crate__api__oxicloud__get_sync_history =
      _wire__crate__api__oxicloud__get_sync_historyPtr.asFunction<void Function(int, int)>();

  void wire__crate__api__oxicloud__get_sync_status(int port_) {
    return _wire__crate__api__oxicloud__get_sync_status(port_);
  }

  late final _wire__crate__api__oxicloud__get_sync_statusPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
    'frbgen_oxicloud_app_wire__crate__api__oxicloud__get_sync_status',
  );
  late final _wire__crate__api__oxicloud__get_sync_status =
      _wire__crate__api__oxicloud__get_sync_statusPtr.asFunction<void Function(int)>();

  WireSyncRust2DartDco wire__crate__api__simple__greet(
    ffi.Pointer<wire_cst_list_prim_u_8_strict> name,
  ) {
    return _wire__crate__api__simple__greet(name);
  }

  late final _wire__crate__api__simple__greetPtr = _lookup<
      ffi.NativeFunction<
          WireSyncRust2DartDco Function(
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )>>('frbgen_oxicloud_app_wire__crate__api__simple__greet');
  late final _wire__crate__api__simple__greet = _wire__crate__api__simple__greetPtr.asFunction<
      WireSyncRust2DartDco Function(
        ffi.Pointer<wire_cst_list_prim_u_8_strict>,
      )>();

  void wire__crate__api__simple__init_app(int port_) {
    return _wire__crate__api__simple__init_app(port_);
  }

  late final _wire__crate__api__simple__init_appPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
    'frbgen_oxicloud_app_wire__crate__api__simple__init_app',
  );
  late final _wire__crate__api__simple__init_app =
      _wire__crate__api__simple__init_appPtr.asFunction<void Function(int)>();

  void wire__crate__api__oxicloud__initialize(
    int port_,
    ffi.Pointer<wire_cst_sync_config> config,
  ) {
    return _wire__crate__api__oxicloud__initialize(port_, config);
  }

  late final _wire__crate__api__oxicloud__initializePtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.Pointer<wire_cst_sync_config>)>>(
          'frbgen_oxicloud_app_wire__crate__api__oxicloud__initialize');
  late final _wire__crate__api__oxicloud__initialize = _wire__crate__api__oxicloud__initializePtr
      .asFunction<void Function(int, ffi.Pointer<wire_cst_sync_config>)>();

  void wire__crate__api__oxicloud__is_logged_in(int port_) {
    return _wire__crate__api__oxicloud__is_logged_in(port_);
  }

  late final _wire__crate__api__oxicloud__is_logged_inPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
    'frbgen_oxicloud_app_wire__crate__api__oxicloud__is_logged_in',
  );
  late final _wire__crate__api__oxicloud__is_logged_in =
      _wire__crate__api__oxicloud__is_logged_inPtr.asFunction<void Function(int)>();

  void wire__crate__api__oxicloud__login(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> server_url,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> username,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> password,
  ) {
    return _wire__crate__api__oxicloud__login(
      port_,
      server_url,
      username,
      password,
    );
  }

  late final _wire__crate__api__oxicloud__loginPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
          )>>('frbgen_oxicloud_app_wire__crate__api__oxicloud__login');
  late final _wire__crate__api__oxicloud__login = _wire__crate__api__oxicloud__loginPtr.asFunction<
      void Function(
        int,
        ffi.Pointer<wire_cst_list_prim_u_8_strict>,
        ffi.Pointer<wire_cst_list_prim_u_8_strict>,
        ffi.Pointer<wire_cst_list_prim_u_8_strict>,
      )>();

  void wire__crate__api__oxicloud__logout(int port_) {
    return _wire__crate__api__oxicloud__logout(port_);
  }

  late final _wire__crate__api__oxicloud__logoutPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
    'frbgen_oxicloud_app_wire__crate__api__oxicloud__logout',
  );
  late final _wire__crate__api__oxicloud__logout =
      _wire__crate__api__oxicloud__logoutPtr.asFunction<void Function(int)>();

  void wire__crate__api__oxicloud__resolve_conflict(
    int port_,
    ffi.Pointer<wire_cst_list_prim_u_8_strict> conflict_id,
    int resolution,
  ) {
    return _wire__crate__api__oxicloud__resolve_conflict(
      port_,
      conflict_id,
      resolution,
    );
  }

  late final _wire__crate__api__oxicloud__resolve_conflictPtr = _lookup<
      ffi.NativeFunction<
          ffi.Void Function(
            ffi.Int64,
            ffi.Pointer<wire_cst_list_prim_u_8_strict>,
            ffi.Int32,
          )>>('frbgen_oxicloud_app_wire__crate__api__oxicloud__resolve_conflict');
  late final _wire__crate__api__oxicloud__resolve_conflict =
      _wire__crate__api__oxicloud__resolve_conflictPtr
          .asFunction<void Function(int, ffi.Pointer<wire_cst_list_prim_u_8_strict>, int)>();

  void wire__crate__api__oxicloud__set_sync_folders(
    int port_,
    ffi.Pointer<wire_cst_list_String> folder_ids,
  ) {
    return _wire__crate__api__oxicloud__set_sync_folders(port_, folder_ids);
  }

  late final _wire__crate__api__oxicloud__set_sync_foldersPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.Pointer<wire_cst_list_String>)>>(
          'frbgen_oxicloud_app_wire__crate__api__oxicloud__set_sync_folders');
  late final _wire__crate__api__oxicloud__set_sync_folders =
      _wire__crate__api__oxicloud__set_sync_foldersPtr
          .asFunction<void Function(int, ffi.Pointer<wire_cst_list_String>)>();

  void wire__crate__api__oxicloud__shutdown(int port_) {
    return _wire__crate__api__oxicloud__shutdown(port_);
  }

  late final _wire__crate__api__oxicloud__shutdownPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
    'frbgen_oxicloud_app_wire__crate__api__oxicloud__shutdown',
  );
  late final _wire__crate__api__oxicloud__shutdown =
      _wire__crate__api__oxicloud__shutdownPtr.asFunction<void Function(int)>();

  void wire__crate__api__oxicloud__start_sync(int port_) {
    return _wire__crate__api__oxicloud__start_sync(port_);
  }

  late final _wire__crate__api__oxicloud__start_syncPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
    'frbgen_oxicloud_app_wire__crate__api__oxicloud__start_sync',
  );
  late final _wire__crate__api__oxicloud__start_sync =
      _wire__crate__api__oxicloud__start_syncPtr.asFunction<void Function(int)>();

  void wire__crate__api__oxicloud__stop_sync(int port_) {
    return _wire__crate__api__oxicloud__stop_sync(port_);
  }

  late final _wire__crate__api__oxicloud__stop_syncPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
    'frbgen_oxicloud_app_wire__crate__api__oxicloud__stop_sync',
  );
  late final _wire__crate__api__oxicloud__stop_sync =
      _wire__crate__api__oxicloud__stop_syncPtr.asFunction<void Function(int)>();

  void wire__crate__api__oxicloud__sync_now(int port_) {
    return _wire__crate__api__oxicloud__sync_now(port_);
  }

  late final _wire__crate__api__oxicloud__sync_nowPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64)>>(
    'frbgen_oxicloud_app_wire__crate__api__oxicloud__sync_now',
  );
  late final _wire__crate__api__oxicloud__sync_now =
      _wire__crate__api__oxicloud__sync_nowPtr.asFunction<void Function(int)>();

  void wire__crate__api__oxicloud__update_config(
    int port_,
    ffi.Pointer<wire_cst_sync_config> config,
  ) {
    return _wire__crate__api__oxicloud__update_config(port_, config);
  }

  late final _wire__crate__api__oxicloud__update_configPtr =
      _lookup<ffi.NativeFunction<ffi.Void Function(ffi.Int64, ffi.Pointer<wire_cst_sync_config>)>>(
          'frbgen_oxicloud_app_wire__crate__api__oxicloud__update_config');
  late final _wire__crate__api__oxicloud__update_config =
      _wire__crate__api__oxicloud__update_configPtr
          .asFunction<void Function(int, ffi.Pointer<wire_cst_sync_config>)>();

  ffi.Pointer<ffi.Int64> cst_new_box_autoadd_Chrono_Utc(int value) {
    return _cst_new_box_autoadd_Chrono_Utc(value);
  }

  late final _cst_new_box_autoadd_Chrono_UtcPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Int64> Function(ffi.Int64)>>(
    'frbgen_oxicloud_app_cst_new_box_autoadd_Chrono_Utc',
  );
  late final _cst_new_box_autoadd_Chrono_Utc =
      _cst_new_box_autoadd_Chrono_UtcPtr.asFunction<ffi.Pointer<ffi.Int64> Function(int)>();

  ffi.Pointer<wire_cst_conflict_info> cst_new_box_autoadd_conflict_info() {
    return _cst_new_box_autoadd_conflict_info();
  }

  late final _cst_new_box_autoadd_conflict_infoPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<wire_cst_conflict_info> Function()>>(
          'frbgen_oxicloud_app_cst_new_box_autoadd_conflict_info');
  late final _cst_new_box_autoadd_conflict_info = _cst_new_box_autoadd_conflict_infoPtr
      .asFunction<ffi.Pointer<wire_cst_conflict_info> Function()>();

  ffi.Pointer<ffi.Int64> cst_new_box_autoadd_i_64(int value) {
    return _cst_new_box_autoadd_i_64(value);
  }

  late final _cst_new_box_autoadd_i_64Ptr =
      _lookup<ffi.NativeFunction<ffi.Pointer<ffi.Int64> Function(ffi.Int64)>>(
    'frbgen_oxicloud_app_cst_new_box_autoadd_i_64',
  );
  late final _cst_new_box_autoadd_i_64 =
      _cst_new_box_autoadd_i_64Ptr.asFunction<ffi.Pointer<ffi.Int64> Function(int)>();

  ffi.Pointer<wire_cst_server_info> cst_new_box_autoadd_server_info() {
    return _cst_new_box_autoadd_server_info();
  }

  late final _cst_new_box_autoadd_server_infoPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<wire_cst_server_info> Function()>>(
    'frbgen_oxicloud_app_cst_new_box_autoadd_server_info',
  );
  late final _cst_new_box_autoadd_server_info = _cst_new_box_autoadd_server_infoPtr
      .asFunction<ffi.Pointer<wire_cst_server_info> Function()>();

  ffi.Pointer<wire_cst_sync_config> cst_new_box_autoadd_sync_config() {
    return _cst_new_box_autoadd_sync_config();
  }

  late final _cst_new_box_autoadd_sync_configPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<wire_cst_sync_config> Function()>>(
    'frbgen_oxicloud_app_cst_new_box_autoadd_sync_config',
  );
  late final _cst_new_box_autoadd_sync_config = _cst_new_box_autoadd_sync_configPtr
      .asFunction<ffi.Pointer<wire_cst_sync_config> Function()>();

  ffi.Pointer<wire_cst_list_String> cst_new_list_String(int len) {
    return _cst_new_list_String(len);
  }

  late final _cst_new_list_StringPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<wire_cst_list_String> Function(ffi.Int32)>>(
          'frbgen_oxicloud_app_cst_new_list_String');
  late final _cst_new_list_String =
      _cst_new_list_StringPtr.asFunction<ffi.Pointer<wire_cst_list_String> Function(int)>();

  ffi.Pointer<wire_cst_list_prim_u_8_strict> cst_new_list_prim_u_8_strict(
    int len,
  ) {
    return _cst_new_list_prim_u_8_strict(len);
  }

  late final _cst_new_list_prim_u_8_strictPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<wire_cst_list_prim_u_8_strict> Function(ffi.Int32)>>(
          'frbgen_oxicloud_app_cst_new_list_prim_u_8_strict');
  late final _cst_new_list_prim_u_8_strict = _cst_new_list_prim_u_8_strictPtr
      .asFunction<ffi.Pointer<wire_cst_list_prim_u_8_strict> Function(int)>();

  ffi.Pointer<wire_cst_list_remote_folder> cst_new_list_remote_folder(int len) {
    return _cst_new_list_remote_folder(len);
  }

  late final _cst_new_list_remote_folderPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<wire_cst_list_remote_folder> Function(ffi.Int32)>>(
          'frbgen_oxicloud_app_cst_new_list_remote_folder');
  late final _cst_new_list_remote_folder = _cst_new_list_remote_folderPtr
      .asFunction<ffi.Pointer<wire_cst_list_remote_folder> Function(int)>();

  ffi.Pointer<wire_cst_list_sync_conflict> cst_new_list_sync_conflict(int len) {
    return _cst_new_list_sync_conflict(len);
  }

  late final _cst_new_list_sync_conflictPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<wire_cst_list_sync_conflict> Function(ffi.Int32)>>(
          'frbgen_oxicloud_app_cst_new_list_sync_conflict');
  late final _cst_new_list_sync_conflict = _cst_new_list_sync_conflictPtr
      .asFunction<ffi.Pointer<wire_cst_list_sync_conflict> Function(int)>();

  ffi.Pointer<wire_cst_list_sync_history_entry> cst_new_list_sync_history_entry(
    int len,
  ) {
    return _cst_new_list_sync_history_entry(len);
  }

  late final _cst_new_list_sync_history_entryPtr = _lookup<
          ffi.NativeFunction<ffi.Pointer<wire_cst_list_sync_history_entry> Function(ffi.Int32)>>(
      'frbgen_oxicloud_app_cst_new_list_sync_history_entry');
  late final _cst_new_list_sync_history_entry = _cst_new_list_sync_history_entryPtr
      .asFunction<ffi.Pointer<wire_cst_list_sync_history_entry> Function(int)>();

  ffi.Pointer<wire_cst_list_sync_item> cst_new_list_sync_item(int len) {
    return _cst_new_list_sync_item(len);
  }

  late final _cst_new_list_sync_itemPtr =
      _lookup<ffi.NativeFunction<ffi.Pointer<wire_cst_list_sync_item> Function(ffi.Int32)>>(
          'frbgen_oxicloud_app_cst_new_list_sync_item');
  late final _cst_new_list_sync_item =
      _cst_new_list_sync_itemPtr.asFunction<ffi.Pointer<wire_cst_list_sync_item> Function(int)>();

  int dummy_method_to_enforce_bundling() {
    return _dummy_method_to_enforce_bundling();
  }

  late final _dummy_method_to_enforce_bundlingPtr =
      _lookup<ffi.NativeFunction<ffi.Int64 Function()>>(
    'dummy_method_to_enforce_bundling',
  );
  late final _dummy_method_to_enforce_bundling =
      _dummy_method_to_enforce_bundlingPtr.asFunction<int Function()>();
}

typedef DartPort = ffi.Int64;
typedef DartDartPort = int;
typedef DartPostCObjectFnTypeFunction = ffi.Bool Function(
    DartPort port_id, ffi.Pointer<ffi.Void> message);
typedef DartDartPostCObjectFnTypeFunction = bool Function(
    DartDartPort port_id, ffi.Pointer<ffi.Void> message);
typedef DartPostCObjectFnType = ffi.Pointer<ffi.NativeFunction<DartPostCObjectFnTypeFunction>>;

final class wire_cst_list_prim_u_8_strict extends ffi.Struct {
  external ffi.Pointer<ffi.Uint8> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_list_String extends ffi.Struct {
  external ffi.Pointer<ffi.Pointer<wire_cst_list_prim_u_8_strict>> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_sync_config extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> sync_folder;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> database_path;

  @ffi.Uint32()
  external int sync_interval_seconds;

  @ffi.Uint32()
  external int max_upload_speed_kbps;

  @ffi.Uint32()
  external int max_download_speed_kbps;

  @ffi.Bool()
  external bool delta_sync_enabled;

  @ffi.Uint64()
  external int delta_sync_min_size;

  @ffi.Bool()
  external bool pause_on_metered;

  @ffi.Bool()
  external bool wifi_only;

  @ffi.Bool()
  external bool watch_filesystem;

  external ffi.Pointer<wire_cst_list_String> ignore_patterns;

  @ffi.Bool()
  external bool notifications_enabled;

  @ffi.Bool()
  external bool launch_at_startup;

  @ffi.Bool()
  external bool minimize_to_tray;
}

final class wire_cst_conflict_info extends ffi.Struct {
  @ffi.Int32()
  external int conflict_type;

  @ffi.Int64()
  external int detected_at;
}

final class wire_cst_server_info extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> url;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> version;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> name;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> webdav_url;

  @ffi.Uint64()
  external int quota_total;

  @ffi.Uint64()
  external int quota_used;

  @ffi.Bool()
  external bool supports_delta_sync;

  @ffi.Bool()
  external bool supports_chunked_upload;
}

final class wire_cst_remote_folder extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> id;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> name;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> path;

  @ffi.Uint64()
  external int size_bytes;

  @ffi.Uint32()
  external int item_count;

  @ffi.Bool()
  external bool is_selected;
}

final class wire_cst_list_remote_folder extends ffi.Struct {
  external ffi.Pointer<wire_cst_remote_folder> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_sync_conflict extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> id;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> item_path;

  @ffi.Int64()
  external int local_modified;

  @ffi.Int64()
  external int remote_modified;

  @ffi.Uint64()
  external int local_size;

  @ffi.Uint64()
  external int remote_size;

  @ffi.Int32()
  external int conflict_type;
}

final class wire_cst_list_sync_conflict extends ffi.Struct {
  external ffi.Pointer<wire_cst_sync_conflict> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_sync_history_entry extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> id;

  @ffi.Int64()
  external int timestamp;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> operation;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> item_path;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> direction;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> status;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> error_message;
}

final class wire_cst_list_sync_history_entry extends ffi.Struct {
  external ffi.Pointer<wire_cst_sync_history_entry> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_SyncStatus_Conflict extends ffi.Struct {
  external ffi.Pointer<wire_cst_conflict_info> field0;
}

final class wire_cst_SyncStatus_Error extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> field0;
}

final class SyncStatusKind extends ffi.Union {
  external wire_cst_SyncStatus_Conflict Conflict;

  external wire_cst_SyncStatus_Error Error;
}

final class wire_cst_sync_status extends ffi.Struct {
  @ffi.Int32()
  external int tag;

  external SyncStatusKind kind;
}

final class wire_cst_sync_item extends ffi.Struct {
  external ffi.Pointer<wire_cst_list_prim_u_8_strict> id;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> path;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> name;

  @ffi.Bool()
  external bool is_directory;

  @ffi.Uint64()
  external int size;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> content_hash;

  external ffi.Pointer<ffi.Int64> local_modified;

  external ffi.Pointer<ffi.Int64> remote_modified;

  external wire_cst_sync_status status;

  @ffi.Int32()
  external int direction;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> etag;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> mime_type;
}

final class wire_cst_list_sync_item extends ffi.Struct {
  external ffi.Pointer<wire_cst_sync_item> ptr;

  @ffi.Int32()
  external int len;
}

final class wire_cst_auth_result extends ffi.Struct {
  @ffi.Bool()
  external bool success;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> user_id;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> username;

  external wire_cst_server_info server_info;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> access_token;
}

final class wire_cst_sync_result extends ffi.Struct {
  @ffi.Bool()
  external bool success;

  @ffi.Uint32()
  external int items_uploaded;

  @ffi.Uint32()
  external int items_downloaded;

  @ffi.Uint32()
  external int items_deleted;

  @ffi.Uint32()
  external int conflicts;

  external ffi.Pointer<wire_cst_list_String> errors;

  @ffi.Uint64()
  external int duration_ms;
}

final class wire_cst_sync_status_info extends ffi.Struct {
  @ffi.Bool()
  external bool is_syncing;

  external ffi.Pointer<wire_cst_list_prim_u_8_strict> current_operation;

  @ffi.Float()
  external double progress_percent;

  @ffi.Uint32()
  external int items_synced;

  @ffi.Uint32()
  external int items_total;

  external ffi.Pointer<ffi.Int64> last_sync_time;

  external ffi.Pointer<ffi.Int64> next_sync_time;
}
