// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/oxicloud.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'domain/entities/auth.dart';
import 'domain/entities/config.dart';
import 'domain/entities/sync_item.dart';
import 'frb_generated.dart';
import 'frb_generated.io.dart' if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
    bool forceSameCodegenVersion = true,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
      forceSameCodegenVersion: forceSameCodegenVersion,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor => RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor => RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateApiSimpleInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.11.1';

  @override
  int get rustContentHash => 55248573;

  static const kDefaultExternalLibraryLoaderConfig = ExternalLibraryLoaderConfig(
    stem: 'oxicloud_core',
    ioDirectory: 'rust/target/release/',
    webPrefix: 'pkg/',
  );
}

abstract class RustLibApi extends BaseApi {
  Future<SyncConfig> crateApiOxicloudGetConfig();

  Future<List<SyncConflict>> crateApiOxicloudGetConflicts();

  Future<List<SyncItem>> crateApiOxicloudGetPendingItems();

  Future<List<RemoteFolder>> crateApiOxicloudGetRemoteFolders();

  Future<ServerInfo?> crateApiOxicloudGetServerInfo();

  Future<List<String>> crateApiOxicloudGetSyncFolders();

  Future<List<SyncHistoryEntry>> crateApiOxicloudGetSyncHistory({required int limit});

  Future<SyncStatusInfo> crateApiOxicloudGetSyncStatus();

  String crateApiSimpleGreet({required String name});

  Future<void> crateApiSimpleInitApp();

  Future<void> crateApiOxicloudInitialize({required SyncConfig config});

  Future<bool> crateApiOxicloudIsLoggedIn();

  Future<AuthResult> crateApiOxicloudLogin(
      {required String serverUrl, required String username, required String password});

  Future<void> crateApiOxicloudLogout();

  Future<void> crateApiOxicloudResolveConflict(
      {required String conflictId, required ConflictResolution resolution});

  Future<void> crateApiOxicloudSetSyncFolders({required List<String> folderIds});

  Future<void> crateApiOxicloudShutdown();

  Future<void> crateApiOxicloudStartSync();

  Future<void> crateApiOxicloudStopSync();

  Future<SyncResult> crateApiOxicloudSyncNow();

  Future<void> crateApiOxicloudUpdateConfig({required SyncConfig config});
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<SyncConfig> crateApiOxicloudGetConfig() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        return wire.wire__crate__api__oxicloud__get_config(port_);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_sync_config,
        decodeErrorData: dco_decode_String,
      ),
      constMeta: kCrateApiOxicloudGetConfigConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiOxicloudGetConfigConstMeta => const TaskConstMeta(
        debugName: "get_config",
        argNames: [],
      );

  @override
  Future<List<SyncConflict>> crateApiOxicloudGetConflicts() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        return wire.wire__crate__api__oxicloud__get_conflicts(port_);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_list_sync_conflict,
        decodeErrorData: dco_decode_String,
      ),
      constMeta: kCrateApiOxicloudGetConflictsConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiOxicloudGetConflictsConstMeta => const TaskConstMeta(
        debugName: "get_conflicts",
        argNames: [],
      );

  @override
  Future<List<SyncItem>> crateApiOxicloudGetPendingItems() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        return wire.wire__crate__api__oxicloud__get_pending_items(port_);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_list_sync_item,
        decodeErrorData: dco_decode_String,
      ),
      constMeta: kCrateApiOxicloudGetPendingItemsConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiOxicloudGetPendingItemsConstMeta => const TaskConstMeta(
        debugName: "get_pending_items",
        argNames: [],
      );

  @override
  Future<List<RemoteFolder>> crateApiOxicloudGetRemoteFolders() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        return wire.wire__crate__api__oxicloud__get_remote_folders(port_);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_list_remote_folder,
        decodeErrorData: dco_decode_String,
      ),
      constMeta: kCrateApiOxicloudGetRemoteFoldersConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiOxicloudGetRemoteFoldersConstMeta => const TaskConstMeta(
        debugName: "get_remote_folders",
        argNames: [],
      );

  @override
  Future<ServerInfo?> crateApiOxicloudGetServerInfo() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        return wire.wire__crate__api__oxicloud__get_server_info(port_);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_opt_box_autoadd_server_info,
        decodeErrorData: dco_decode_String,
      ),
      constMeta: kCrateApiOxicloudGetServerInfoConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiOxicloudGetServerInfoConstMeta => const TaskConstMeta(
        debugName: "get_server_info",
        argNames: [],
      );

  @override
  Future<List<String>> crateApiOxicloudGetSyncFolders() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        return wire.wire__crate__api__oxicloud__get_sync_folders(port_);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_list_String,
        decodeErrorData: dco_decode_String,
      ),
      constMeta: kCrateApiOxicloudGetSyncFoldersConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiOxicloudGetSyncFoldersConstMeta => const TaskConstMeta(
        debugName: "get_sync_folders",
        argNames: [],
      );

  @override
  Future<List<SyncHistoryEntry>> crateApiOxicloudGetSyncHistory({required int limit}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        var arg0 = cst_encode_u_32(limit);
        return wire.wire__crate__api__oxicloud__get_sync_history(port_, arg0);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_list_sync_history_entry,
        decodeErrorData: dco_decode_String,
      ),
      constMeta: kCrateApiOxicloudGetSyncHistoryConstMeta,
      argValues: [limit],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiOxicloudGetSyncHistoryConstMeta => const TaskConstMeta(
        debugName: "get_sync_history",
        argNames: ["limit"],
      );

  @override
  Future<SyncStatusInfo> crateApiOxicloudGetSyncStatus() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        return wire.wire__crate__api__oxicloud__get_sync_status(port_);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_sync_status_info,
        decodeErrorData: dco_decode_String,
      ),
      constMeta: kCrateApiOxicloudGetSyncStatusConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiOxicloudGetSyncStatusConstMeta => const TaskConstMeta(
        debugName: "get_sync_status",
        argNames: [],
      );

  @override
  String crateApiSimpleGreet({required String name}) {
    return handler.executeSync(SyncTask(
      callFfi: () {
        var arg0 = cst_encode_String(name);
        return wire.wire__crate__api__simple__greet(arg0);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_String,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSimpleGreetConstMeta,
      argValues: [name],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleGreetConstMeta => const TaskConstMeta(
        debugName: "greet",
        argNames: ["name"],
      );

  @override
  Future<void> crateApiSimpleInitApp() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        return wire.wire__crate__api__simple__init_app(port_);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateApiSimpleInitAppConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiSimpleInitAppConstMeta => const TaskConstMeta(
        debugName: "init_app",
        argNames: [],
      );

  @override
  Future<void> crateApiOxicloudInitialize({required SyncConfig config}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        var arg0 = cst_encode_box_autoadd_sync_config(config);
        return wire.wire__crate__api__oxicloud__initialize(port_, arg0);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_unit,
        decodeErrorData: dco_decode_String,
      ),
      constMeta: kCrateApiOxicloudInitializeConstMeta,
      argValues: [config],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiOxicloudInitializeConstMeta => const TaskConstMeta(
        debugName: "initialize",
        argNames: ["config"],
      );

  @override
  Future<bool> crateApiOxicloudIsLoggedIn() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        return wire.wire__crate__api__oxicloud__is_logged_in(port_);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_bool,
        decodeErrorData: dco_decode_String,
      ),
      constMeta: kCrateApiOxicloudIsLoggedInConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiOxicloudIsLoggedInConstMeta => const TaskConstMeta(
        debugName: "is_logged_in",
        argNames: [],
      );

  @override
  Future<AuthResult> crateApiOxicloudLogin(
      {required String serverUrl, required String username, required String password}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        var arg0 = cst_encode_String(serverUrl);
        var arg1 = cst_encode_String(username);
        var arg2 = cst_encode_String(password);
        return wire.wire__crate__api__oxicloud__login(port_, arg0, arg1, arg2);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_auth_result,
        decodeErrorData: dco_decode_String,
      ),
      constMeta: kCrateApiOxicloudLoginConstMeta,
      argValues: [serverUrl, username, password],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiOxicloudLoginConstMeta => const TaskConstMeta(
        debugName: "login",
        argNames: ["serverUrl", "username", "password"],
      );

  @override
  Future<void> crateApiOxicloudLogout() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        return wire.wire__crate__api__oxicloud__logout(port_);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_unit,
        decodeErrorData: dco_decode_String,
      ),
      constMeta: kCrateApiOxicloudLogoutConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiOxicloudLogoutConstMeta => const TaskConstMeta(
        debugName: "logout",
        argNames: [],
      );

  @override
  Future<void> crateApiOxicloudResolveConflict(
      {required String conflictId, required ConflictResolution resolution}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        var arg0 = cst_encode_String(conflictId);
        var arg1 = cst_encode_conflict_resolution(resolution);
        return wire.wire__crate__api__oxicloud__resolve_conflict(port_, arg0, arg1);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_unit,
        decodeErrorData: dco_decode_String,
      ),
      constMeta: kCrateApiOxicloudResolveConflictConstMeta,
      argValues: [conflictId, resolution],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiOxicloudResolveConflictConstMeta => const TaskConstMeta(
        debugName: "resolve_conflict",
        argNames: ["conflictId", "resolution"],
      );

  @override
  Future<void> crateApiOxicloudSetSyncFolders({required List<String> folderIds}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        var arg0 = cst_encode_list_String(folderIds);
        return wire.wire__crate__api__oxicloud__set_sync_folders(port_, arg0);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_unit,
        decodeErrorData: dco_decode_String,
      ),
      constMeta: kCrateApiOxicloudSetSyncFoldersConstMeta,
      argValues: [folderIds],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiOxicloudSetSyncFoldersConstMeta => const TaskConstMeta(
        debugName: "set_sync_folders",
        argNames: ["folderIds"],
      );

  @override
  Future<void> crateApiOxicloudShutdown() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        return wire.wire__crate__api__oxicloud__shutdown(port_);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_unit,
        decodeErrorData: dco_decode_String,
      ),
      constMeta: kCrateApiOxicloudShutdownConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiOxicloudShutdownConstMeta => const TaskConstMeta(
        debugName: "shutdown",
        argNames: [],
      );

  @override
  Future<void> crateApiOxicloudStartSync() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        return wire.wire__crate__api__oxicloud__start_sync(port_);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_unit,
        decodeErrorData: dco_decode_String,
      ),
      constMeta: kCrateApiOxicloudStartSyncConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiOxicloudStartSyncConstMeta => const TaskConstMeta(
        debugName: "start_sync",
        argNames: [],
      );

  @override
  Future<void> crateApiOxicloudStopSync() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        return wire.wire__crate__api__oxicloud__stop_sync(port_);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_unit,
        decodeErrorData: dco_decode_String,
      ),
      constMeta: kCrateApiOxicloudStopSyncConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiOxicloudStopSyncConstMeta => const TaskConstMeta(
        debugName: "stop_sync",
        argNames: [],
      );

  @override
  Future<SyncResult> crateApiOxicloudSyncNow() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        return wire.wire__crate__api__oxicloud__sync_now(port_);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_sync_result,
        decodeErrorData: dco_decode_String,
      ),
      constMeta: kCrateApiOxicloudSyncNowConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiOxicloudSyncNowConstMeta => const TaskConstMeta(
        debugName: "sync_now",
        argNames: [],
      );

  @override
  Future<void> crateApiOxicloudUpdateConfig({required SyncConfig config}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        var arg0 = cst_encode_box_autoadd_sync_config(config);
        return wire.wire__crate__api__oxicloud__update_config(port_, arg0);
      },
      codec: DcoCodec(
        decodeSuccessData: dco_decode_unit,
        decodeErrorData: dco_decode_String,
      ),
      constMeta: kCrateApiOxicloudUpdateConfigConstMeta,
      argValues: [config],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiOxicloudUpdateConfigConstMeta => const TaskConstMeta(
        debugName: "update_config",
        argNames: ["config"],
      );

  @protected
  DateTime dco_decode_Chrono_Utc(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeTimestamp(ts: dco_decode_i_64(raw).toInt(), isUtc: true);
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  AuthResult dco_decode_auth_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 5) throw Exception('unexpected arr length: expect 5 but see ${arr.length}');
    return AuthResult(
      success: dco_decode_bool(arr[0]),
      userId: dco_decode_String(arr[1]),
      username: dco_decode_String(arr[2]),
      serverInfo: dco_decode_server_info(arr[3]),
      accessToken: dco_decode_String(arr[4]),
    );
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  DateTime dco_decode_box_autoadd_Chrono_Utc(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_Chrono_Utc(raw);
  }

  @protected
  ConflictInfo dco_decode_box_autoadd_conflict_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_conflict_info(raw);
  }

  @protected
  PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_i_64(raw);
  }

  @protected
  ServerInfo dco_decode_box_autoadd_server_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_server_info(raw);
  }

  @protected
  SyncConfig dco_decode_box_autoadd_sync_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_sync_config(raw);
  }

  @protected
  ConflictInfo dco_decode_conflict_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2) throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return ConflictInfo(
      conflictType: dco_decode_conflict_type(arr[0]),
      detectedAt: dco_decode_Chrono_Utc(arr[1]),
    );
  }

  @protected
  ConflictResolution dco_decode_conflict_resolution(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ConflictResolution.values[raw as int];
  }

  @protected
  ConflictType dco_decode_conflict_type(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return ConflictType.values[raw as int];
  }

  @protected
  double dco_decode_f_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as double;
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  PlatformInt64 dco_decode_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeI64(raw);
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  List<RemoteFolder> dco_decode_list_remote_folder(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_remote_folder).toList();
  }

  @protected
  List<SyncConflict> dco_decode_list_sync_conflict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_sync_conflict).toList();
  }

  @protected
  List<SyncHistoryEntry> dco_decode_list_sync_history_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_sync_history_entry).toList();
  }

  @protected
  List<SyncItem> dco_decode_list_sync_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_sync_item).toList();
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  DateTime? dco_decode_opt_box_autoadd_Chrono_Utc(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_Chrono_Utc(raw);
  }

  @protected
  PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_i_64(raw);
  }

  @protected
  ServerInfo? dco_decode_opt_box_autoadd_server_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_server_info(raw);
  }

  @protected
  RemoteFolder dco_decode_remote_folder(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6) throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return RemoteFolder(
      id: dco_decode_String(arr[0]),
      name: dco_decode_String(arr[1]),
      path: dco_decode_String(arr[2]),
      sizeBytes: dco_decode_u_64(arr[3]),
      itemCount: dco_decode_u_32(arr[4]),
      isSelected: dco_decode_bool(arr[5]),
    );
  }

  @protected
  ServerInfo dco_decode_server_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8) throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return ServerInfo(
      url: dco_decode_String(arr[0]),
      version: dco_decode_String(arr[1]),
      name: dco_decode_String(arr[2]),
      webdavUrl: dco_decode_String(arr[3]),
      quotaTotal: dco_decode_u_64(arr[4]),
      quotaUsed: dco_decode_u_64(arr[5]),
      supportsDeltaSync: dco_decode_bool(arr[6]),
      supportsChunkedUpload: dco_decode_bool(arr[7]),
    );
  }

  @protected
  SyncConfig dco_decode_sync_config(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 14) throw Exception('unexpected arr length: expect 14 but see ${arr.length}');
    return SyncConfig(
      syncFolder: dco_decode_String(arr[0]),
      databasePath: dco_decode_String(arr[1]),
      syncIntervalSeconds: dco_decode_u_32(arr[2]),
      maxUploadSpeedKbps: dco_decode_u_32(arr[3]),
      maxDownloadSpeedKbps: dco_decode_u_32(arr[4]),
      deltaSyncEnabled: dco_decode_bool(arr[5]),
      deltaSyncMinSize: dco_decode_u_64(arr[6]),
      pauseOnMetered: dco_decode_bool(arr[7]),
      wifiOnly: dco_decode_bool(arr[8]),
      watchFilesystem: dco_decode_bool(arr[9]),
      ignorePatterns: dco_decode_list_String(arr[10]),
      notificationsEnabled: dco_decode_bool(arr[11]),
      launchAtStartup: dco_decode_bool(arr[12]),
      minimizeToTray: dco_decode_bool(arr[13]),
    );
  }

  @protected
  SyncConflict dco_decode_sync_conflict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7) throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return SyncConflict(
      id: dco_decode_String(arr[0]),
      itemPath: dco_decode_String(arr[1]),
      localModified: dco_decode_i_64(arr[2]),
      remoteModified: dco_decode_i_64(arr[3]),
      localSize: dco_decode_u_64(arr[4]),
      remoteSize: dco_decode_u_64(arr[5]),
      conflictType: dco_decode_conflict_type(arr[6]),
    );
  }

  @protected
  SyncDirection dco_decode_sync_direction(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return SyncDirection.values[raw as int];
  }

  @protected
  SyncHistoryEntry dco_decode_sync_history_entry(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7) throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return SyncHistoryEntry(
      id: dco_decode_String(arr[0]),
      timestamp: dco_decode_i_64(arr[1]),
      operation: dco_decode_String(arr[2]),
      itemPath: dco_decode_String(arr[3]),
      direction: dco_decode_String(arr[4]),
      status: dco_decode_String(arr[5]),
      errorMessage: dco_decode_opt_String(arr[6]),
    );
  }

  @protected
  SyncItem dco_decode_sync_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 12) throw Exception('unexpected arr length: expect 12 but see ${arr.length}');
    return SyncItem(
      id: dco_decode_String(arr[0]),
      path: dco_decode_String(arr[1]),
      name: dco_decode_String(arr[2]),
      isDirectory: dco_decode_bool(arr[3]),
      size: dco_decode_u_64(arr[4]),
      contentHash: dco_decode_opt_String(arr[5]),
      localModified: dco_decode_opt_box_autoadd_Chrono_Utc(arr[6]),
      remoteModified: dco_decode_opt_box_autoadd_Chrono_Utc(arr[7]),
      status: dco_decode_sync_status(arr[8]),
      direction: dco_decode_sync_direction(arr[9]),
      etag: dco_decode_opt_String(arr[10]),
      mimeType: dco_decode_opt_String(arr[11]),
    );
  }

  @protected
  SyncResult dco_decode_sync_result(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7) throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return SyncResult(
      success: dco_decode_bool(arr[0]),
      itemsUploaded: dco_decode_u_32(arr[1]),
      itemsDownloaded: dco_decode_u_32(arr[2]),
      itemsDeleted: dco_decode_u_32(arr[3]),
      conflicts: dco_decode_u_32(arr[4]),
      errors: dco_decode_list_String(arr[5]),
      durationMs: dco_decode_u_64(arr[6]),
    );
  }

  @protected
  SyncStatus dco_decode_sync_status(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    switch (raw[0]) {
      case 0:
        return SyncStatus_Synced();
      case 1:
        return SyncStatus_Pending();
      case 2:
        return SyncStatus_Syncing();
      case 3:
        return SyncStatus_Conflict(
          dco_decode_box_autoadd_conflict_info(raw[1]),
        );
      case 4:
        return SyncStatus_Error(
          dco_decode_String(raw[1]),
        );
      case 5:
        return SyncStatus_Ignored();
      default:
        throw Exception("unreachable");
    }
  }

  @protected
  SyncStatusInfo dco_decode_sync_status_info(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7) throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return SyncStatusInfo(
      isSyncing: dco_decode_bool(arr[0]),
      currentOperation: dco_decode_opt_String(arr[1]),
      progressPercent: dco_decode_f_32(arr[2]),
      itemsSynced: dco_decode_u_32(arr[3]),
      itemsTotal: dco_decode_u_32(arr[4]),
      lastSyncTime: dco_decode_opt_box_autoadd_i_64(arr[5]),
      nextSyncTime: dco_decode_opt_box_autoadd_i_64(arr[6]),
    );
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  DateTime sse_decode_Chrono_Utc(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_64(deserializer);
    return DateTime.fromMicrosecondsSinceEpoch(inner.toInt(), isUtc: true);
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  AuthResult sse_decode_auth_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_success = sse_decode_bool(deserializer);
    var var_userId = sse_decode_String(deserializer);
    var var_username = sse_decode_String(deserializer);
    var var_serverInfo = sse_decode_server_info(deserializer);
    var var_accessToken = sse_decode_String(deserializer);
    return AuthResult(
        success: var_success,
        userId: var_userId,
        username: var_username,
        serverInfo: var_serverInfo,
        accessToken: var_accessToken);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  DateTime sse_decode_box_autoadd_Chrono_Utc(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_Chrono_Utc(deserializer));
  }

  @protected
  ConflictInfo sse_decode_box_autoadd_conflict_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_conflict_info(deserializer));
  }

  @protected
  PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_i_64(deserializer));
  }

  @protected
  ServerInfo sse_decode_box_autoadd_server_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_server_info(deserializer));
  }

  @protected
  SyncConfig sse_decode_box_autoadd_sync_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_sync_config(deserializer));
  }

  @protected
  ConflictInfo sse_decode_conflict_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_conflictType = sse_decode_conflict_type(deserializer);
    var var_detectedAt = sse_decode_Chrono_Utc(deserializer);
    return ConflictInfo(conflictType: var_conflictType, detectedAt: var_detectedAt);
  }

  @protected
  ConflictResolution sse_decode_conflict_resolution(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return ConflictResolution.values[inner];
  }

  @protected
  ConflictType sse_decode_conflict_type(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return ConflictType.values[inner];
  }

  @protected
  double sse_decode_f_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getFloat32();
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  PlatformInt64 sse_decode_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getPlatformInt64();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  List<RemoteFolder> sse_decode_list_remote_folder(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <RemoteFolder>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_remote_folder(deserializer));
    }
    return ans_;
  }

  @protected
  List<SyncConflict> sse_decode_list_sync_conflict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SyncConflict>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_sync_conflict(deserializer));
    }
    return ans_;
  }

  @protected
  List<SyncHistoryEntry> sse_decode_list_sync_history_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SyncHistoryEntry>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_sync_history_entry(deserializer));
    }
    return ans_;
  }

  @protected
  List<SyncItem> sse_decode_list_sync_item(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <SyncItem>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_sync_item(deserializer));
    }
    return ans_;
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  DateTime? sse_decode_opt_box_autoadd_Chrono_Utc(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_Chrono_Utc(deserializer));
    } else {
      return null;
    }
  }

  @protected
  PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_i_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  ServerInfo? sse_decode_opt_box_autoadd_server_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_server_info(deserializer));
    } else {
      return null;
    }
  }

  @protected
  RemoteFolder sse_decode_remote_folder(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_path = sse_decode_String(deserializer);
    var var_sizeBytes = sse_decode_u_64(deserializer);
    var var_itemCount = sse_decode_u_32(deserializer);
    var var_isSelected = sse_decode_bool(deserializer);
    return RemoteFolder(
        id: var_id,
        name: var_name,
        path: var_path,
        sizeBytes: var_sizeBytes,
        itemCount: var_itemCount,
        isSelected: var_isSelected);
  }

  @protected
  ServerInfo sse_decode_server_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_url = sse_decode_String(deserializer);
    var var_version = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_webdavUrl = sse_decode_String(deserializer);
    var var_quotaTotal = sse_decode_u_64(deserializer);
    var var_quotaUsed = sse_decode_u_64(deserializer);
    var var_supportsDeltaSync = sse_decode_bool(deserializer);
    var var_supportsChunkedUpload = sse_decode_bool(deserializer);
    return ServerInfo(
        url: var_url,
        version: var_version,
        name: var_name,
        webdavUrl: var_webdavUrl,
        quotaTotal: var_quotaTotal,
        quotaUsed: var_quotaUsed,
        supportsDeltaSync: var_supportsDeltaSync,
        supportsChunkedUpload: var_supportsChunkedUpload);
  }

  @protected
  SyncConfig sse_decode_sync_config(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_syncFolder = sse_decode_String(deserializer);
    var var_databasePath = sse_decode_String(deserializer);
    var var_syncIntervalSeconds = sse_decode_u_32(deserializer);
    var var_maxUploadSpeedKbps = sse_decode_u_32(deserializer);
    var var_maxDownloadSpeedKbps = sse_decode_u_32(deserializer);
    var var_deltaSyncEnabled = sse_decode_bool(deserializer);
    var var_deltaSyncMinSize = sse_decode_u_64(deserializer);
    var var_pauseOnMetered = sse_decode_bool(deserializer);
    var var_wifiOnly = sse_decode_bool(deserializer);
    var var_watchFilesystem = sse_decode_bool(deserializer);
    var var_ignorePatterns = sse_decode_list_String(deserializer);
    var var_notificationsEnabled = sse_decode_bool(deserializer);
    var var_launchAtStartup = sse_decode_bool(deserializer);
    var var_minimizeToTray = sse_decode_bool(deserializer);
    return SyncConfig(
        syncFolder: var_syncFolder,
        databasePath: var_databasePath,
        syncIntervalSeconds: var_syncIntervalSeconds,
        maxUploadSpeedKbps: var_maxUploadSpeedKbps,
        maxDownloadSpeedKbps: var_maxDownloadSpeedKbps,
        deltaSyncEnabled: var_deltaSyncEnabled,
        deltaSyncMinSize: var_deltaSyncMinSize,
        pauseOnMetered: var_pauseOnMetered,
        wifiOnly: var_wifiOnly,
        watchFilesystem: var_watchFilesystem,
        ignorePatterns: var_ignorePatterns,
        notificationsEnabled: var_notificationsEnabled,
        launchAtStartup: var_launchAtStartup,
        minimizeToTray: var_minimizeToTray);
  }

  @protected
  SyncConflict sse_decode_sync_conflict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_itemPath = sse_decode_String(deserializer);
    var var_localModified = sse_decode_i_64(deserializer);
    var var_remoteModified = sse_decode_i_64(deserializer);
    var var_localSize = sse_decode_u_64(deserializer);
    var var_remoteSize = sse_decode_u_64(deserializer);
    var var_conflictType = sse_decode_conflict_type(deserializer);
    return SyncConflict(
        id: var_id,
        itemPath: var_itemPath,
        localModified: var_localModified,
        remoteModified: var_remoteModified,
        localSize: var_localSize,
        remoteSize: var_remoteSize,
        conflictType: var_conflictType);
  }

  @protected
  SyncDirection sse_decode_sync_direction(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return SyncDirection.values[inner];
  }

  @protected
  SyncHistoryEntry sse_decode_sync_history_entry(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_timestamp = sse_decode_i_64(deserializer);
    var var_operation = sse_decode_String(deserializer);
    var var_itemPath = sse_decode_String(deserializer);
    var var_direction = sse_decode_String(deserializer);
    var var_status = sse_decode_String(deserializer);
    var var_errorMessage = sse_decode_opt_String(deserializer);
    return SyncHistoryEntry(
        id: var_id,
        timestamp: var_timestamp,
        operation: var_operation,
        itemPath: var_itemPath,
        direction: var_direction,
        status: var_status,
        errorMessage: var_errorMessage);
  }

  @protected
  SyncItem sse_decode_sync_item(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_path = sse_decode_String(deserializer);
    var var_name = sse_decode_String(deserializer);
    var var_isDirectory = sse_decode_bool(deserializer);
    var var_size = sse_decode_u_64(deserializer);
    var var_contentHash = sse_decode_opt_String(deserializer);
    var var_localModified = sse_decode_opt_box_autoadd_Chrono_Utc(deserializer);
    var var_remoteModified = sse_decode_opt_box_autoadd_Chrono_Utc(deserializer);
    var var_status = sse_decode_sync_status(deserializer);
    var var_direction = sse_decode_sync_direction(deserializer);
    var var_etag = sse_decode_opt_String(deserializer);
    var var_mimeType = sse_decode_opt_String(deserializer);
    return SyncItem(
        id: var_id,
        path: var_path,
        name: var_name,
        isDirectory: var_isDirectory,
        size: var_size,
        contentHash: var_contentHash,
        localModified: var_localModified,
        remoteModified: var_remoteModified,
        status: var_status,
        direction: var_direction,
        etag: var_etag,
        mimeType: var_mimeType);
  }

  @protected
  SyncResult sse_decode_sync_result(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_success = sse_decode_bool(deserializer);
    var var_itemsUploaded = sse_decode_u_32(deserializer);
    var var_itemsDownloaded = sse_decode_u_32(deserializer);
    var var_itemsDeleted = sse_decode_u_32(deserializer);
    var var_conflicts = sse_decode_u_32(deserializer);
    var var_errors = sse_decode_list_String(deserializer);
    var var_durationMs = sse_decode_u_64(deserializer);
    return SyncResult(
        success: var_success,
        itemsUploaded: var_itemsUploaded,
        itemsDownloaded: var_itemsDownloaded,
        itemsDeleted: var_itemsDeleted,
        conflicts: var_conflicts,
        errors: var_errors,
        durationMs: var_durationMs);
  }

  @protected
  SyncStatus sse_decode_sync_status(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var tag_ = sse_decode_i_32(deserializer);
    switch (tag_) {
      case 0:
        return SyncStatus_Synced();
      case 1:
        return SyncStatus_Pending();
      case 2:
        return SyncStatus_Syncing();
      case 3:
        var var_field0 = sse_decode_box_autoadd_conflict_info(deserializer);
        return SyncStatus_Conflict(var_field0);
      case 4:
        var var_field0 = sse_decode_String(deserializer);
        return SyncStatus_Error(var_field0);
      case 5:
        return SyncStatus_Ignored();
      default:
        throw UnimplementedError('');
    }
  }

  @protected
  SyncStatusInfo sse_decode_sync_status_info(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_isSyncing = sse_decode_bool(deserializer);
    var var_currentOperation = sse_decode_opt_String(deserializer);
    var var_progressPercent = sse_decode_f_32(deserializer);
    var var_itemsSynced = sse_decode_u_32(deserializer);
    var var_itemsTotal = sse_decode_u_32(deserializer);
    var var_lastSyncTime = sse_decode_opt_box_autoadd_i_64(deserializer);
    var var_nextSyncTime = sse_decode_opt_box_autoadd_i_64(deserializer);
    return SyncStatusInfo(
        isSyncing: var_isSyncing,
        currentOperation: var_currentOperation,
        progressPercent: var_progressPercent,
        itemsSynced: var_itemsSynced,
        itemsTotal: var_itemsTotal,
        lastSyncTime: var_lastSyncTime,
        nextSyncTime: var_nextSyncTime);
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  bool cst_encode_bool(bool raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  int cst_encode_conflict_resolution(ConflictResolution raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_i_32(raw.index);
  }

  @protected
  int cst_encode_conflict_type(ConflictType raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_i_32(raw.index);
  }

  @protected
  double cst_encode_f_32(double raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  int cst_encode_i_32(int raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  int cst_encode_sync_direction(SyncDirection raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return cst_encode_i_32(raw.index);
  }

  @protected
  int cst_encode_u_32(int raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  int cst_encode_u_8(int raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  void cst_encode_unit(void raw) {
    // Codec=Cst (C-struct based), see doc to use other codecs
    return raw;
  }

  @protected
  void sse_encode_Chrono_Utc(DateTime self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(PlatformInt64Util.from(self.microsecondsSinceEpoch), serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_auth_result(AuthResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.success, serializer);
    sse_encode_String(self.userId, serializer);
    sse_encode_String(self.username, serializer);
    sse_encode_server_info(self.serverInfo, serializer);
    sse_encode_String(self.accessToken, serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_Chrono_Utc(DateTime self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_Chrono_Utc(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_conflict_info(ConflictInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_conflict_info(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_64(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_server_info(ServerInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_server_info(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_sync_config(SyncConfig self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_sync_config(self, serializer);
  }

  @protected
  void sse_encode_conflict_info(ConflictInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_conflict_type(self.conflictType, serializer);
    sse_encode_Chrono_Utc(self.detectedAt, serializer);
  }

  @protected
  void sse_encode_conflict_resolution(ConflictResolution self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_conflict_type(ConflictType self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_f_32(double self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putFloat32(self);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putPlatformInt64(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_list_remote_folder(List<RemoteFolder> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_remote_folder(item, serializer);
    }
  }

  @protected
  void sse_encode_list_sync_conflict(List<SyncConflict> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_sync_conflict(item, serializer);
    }
  }

  @protected
  void sse_encode_list_sync_history_entry(List<SyncHistoryEntry> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_sync_history_entry(item, serializer);
    }
  }

  @protected
  void sse_encode_list_sync_item(List<SyncItem> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_sync_item(item, serializer);
    }
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_Chrono_Utc(DateTime? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_Chrono_Utc(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_i_64(PlatformInt64? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_i_64(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_server_info(ServerInfo? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_server_info(self, serializer);
    }
  }

  @protected
  void sse_encode_remote_folder(RemoteFolder self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.path, serializer);
    sse_encode_u_64(self.sizeBytes, serializer);
    sse_encode_u_32(self.itemCount, serializer);
    sse_encode_bool(self.isSelected, serializer);
  }

  @protected
  void sse_encode_server_info(ServerInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.url, serializer);
    sse_encode_String(self.version, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_String(self.webdavUrl, serializer);
    sse_encode_u_64(self.quotaTotal, serializer);
    sse_encode_u_64(self.quotaUsed, serializer);
    sse_encode_bool(self.supportsDeltaSync, serializer);
    sse_encode_bool(self.supportsChunkedUpload, serializer);
  }

  @protected
  void sse_encode_sync_config(SyncConfig self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.syncFolder, serializer);
    sse_encode_String(self.databasePath, serializer);
    sse_encode_u_32(self.syncIntervalSeconds, serializer);
    sse_encode_u_32(self.maxUploadSpeedKbps, serializer);
    sse_encode_u_32(self.maxDownloadSpeedKbps, serializer);
    sse_encode_bool(self.deltaSyncEnabled, serializer);
    sse_encode_u_64(self.deltaSyncMinSize, serializer);
    sse_encode_bool(self.pauseOnMetered, serializer);
    sse_encode_bool(self.wifiOnly, serializer);
    sse_encode_bool(self.watchFilesystem, serializer);
    sse_encode_list_String(self.ignorePatterns, serializer);
    sse_encode_bool(self.notificationsEnabled, serializer);
    sse_encode_bool(self.launchAtStartup, serializer);
    sse_encode_bool(self.minimizeToTray, serializer);
  }

  @protected
  void sse_encode_sync_conflict(SyncConflict self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.itemPath, serializer);
    sse_encode_i_64(self.localModified, serializer);
    sse_encode_i_64(self.remoteModified, serializer);
    sse_encode_u_64(self.localSize, serializer);
    sse_encode_u_64(self.remoteSize, serializer);
    sse_encode_conflict_type(self.conflictType, serializer);
  }

  @protected
  void sse_encode_sync_direction(SyncDirection self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_sync_history_entry(SyncHistoryEntry self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_i_64(self.timestamp, serializer);
    sse_encode_String(self.operation, serializer);
    sse_encode_String(self.itemPath, serializer);
    sse_encode_String(self.direction, serializer);
    sse_encode_String(self.status, serializer);
    sse_encode_opt_String(self.errorMessage, serializer);
  }

  @protected
  void sse_encode_sync_item(SyncItem self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.path, serializer);
    sse_encode_String(self.name, serializer);
    sse_encode_bool(self.isDirectory, serializer);
    sse_encode_u_64(self.size, serializer);
    sse_encode_opt_String(self.contentHash, serializer);
    sse_encode_opt_box_autoadd_Chrono_Utc(self.localModified, serializer);
    sse_encode_opt_box_autoadd_Chrono_Utc(self.remoteModified, serializer);
    sse_encode_sync_status(self.status, serializer);
    sse_encode_sync_direction(self.direction, serializer);
    sse_encode_opt_String(self.etag, serializer);
    sse_encode_opt_String(self.mimeType, serializer);
  }

  @protected
  void sse_encode_sync_result(SyncResult self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.success, serializer);
    sse_encode_u_32(self.itemsUploaded, serializer);
    sse_encode_u_32(self.itemsDownloaded, serializer);
    sse_encode_u_32(self.itemsDeleted, serializer);
    sse_encode_u_32(self.conflicts, serializer);
    sse_encode_list_String(self.errors, serializer);
    sse_encode_u_64(self.durationMs, serializer);
  }

  @protected
  void sse_encode_sync_status(SyncStatus self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    switch (self) {
      case SyncStatus_Synced():
        sse_encode_i_32(0, serializer);
      case SyncStatus_Pending():
        sse_encode_i_32(1, serializer);
      case SyncStatus_Syncing():
        sse_encode_i_32(2, serializer);
      case SyncStatus_Conflict(field0: final field0):
        sse_encode_i_32(3, serializer);
        sse_encode_box_autoadd_conflict_info(field0, serializer);
      case SyncStatus_Error(field0: final field0):
        sse_encode_i_32(4, serializer);
        sse_encode_String(field0, serializer);
      case SyncStatus_Ignored():
        sse_encode_i_32(5, serializer);
    }
  }

  @protected
  void sse_encode_sync_status_info(SyncStatusInfo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_bool(self.isSyncing, serializer);
    sse_encode_opt_String(self.currentOperation, serializer);
    sse_encode_f_32(self.progressPercent, serializer);
    sse_encode_u_32(self.itemsSynced, serializer);
    sse_encode_u_32(self.itemsTotal, serializer);
    sse_encode_opt_box_autoadd_i_64(self.lastSyncTime, serializer);
    sse_encode_opt_box_autoadd_i_64(self.nextSyncTime, serializer);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }
}
