// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field


// Static analysis wrongly picks the IO variant, thus ignore this
// ignore_for_file: argument_type_not_assignable

import 'api/oxicloud.dart';
import 'api/simple.dart';
import 'dart:async';
import 'dart:convert';
import 'domain/entities/auth.dart';
import 'domain/entities/config.dart';
import 'domain/entities/sync_item.dart';
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_web.dart';




                abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
                  RustLibApiImplPlatform({
                    required super.handler,
                    required super.wire,
                    required super.generalizedFrbRustBinding,
                    required super.portManager,
                  });

                  

                  @protected DateTime dco_decode_Chrono_Utc(dynamic raw);

@protected String dco_decode_String(dynamic raw);

@protected AuthResult dco_decode_auth_result(dynamic raw);

@protected bool dco_decode_bool(dynamic raw);

@protected DateTime dco_decode_box_autoadd_Chrono_Utc(dynamic raw);

@protected ConflictInfo dco_decode_box_autoadd_conflict_info(dynamic raw);

@protected PlatformInt64 dco_decode_box_autoadd_i_64(dynamic raw);

@protected ServerInfo dco_decode_box_autoadd_server_info(dynamic raw);

@protected SyncConfig dco_decode_box_autoadd_sync_config(dynamic raw);

@protected ConflictInfo dco_decode_conflict_info(dynamic raw);

@protected ConflictResolution dco_decode_conflict_resolution(dynamic raw);

@protected ConflictType dco_decode_conflict_type(dynamic raw);

@protected double dco_decode_f_32(dynamic raw);

@protected int dco_decode_i_32(dynamic raw);

@protected PlatformInt64 dco_decode_i_64(dynamic raw);

@protected List<String> dco_decode_list_String(dynamic raw);

@protected Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

@protected List<RemoteFolder> dco_decode_list_remote_folder(dynamic raw);

@protected List<SyncConflict> dco_decode_list_sync_conflict(dynamic raw);

@protected List<SyncHistoryEntry> dco_decode_list_sync_history_entry(dynamic raw);

@protected List<SyncItem> dco_decode_list_sync_item(dynamic raw);

@protected String? dco_decode_opt_String(dynamic raw);

@protected DateTime? dco_decode_opt_box_autoadd_Chrono_Utc(dynamic raw);

@protected PlatformInt64? dco_decode_opt_box_autoadd_i_64(dynamic raw);

@protected ServerInfo? dco_decode_opt_box_autoadd_server_info(dynamic raw);

@protected RemoteFolder dco_decode_remote_folder(dynamic raw);

@protected ServerInfo dco_decode_server_info(dynamic raw);

@protected SyncConfig dco_decode_sync_config(dynamic raw);

@protected SyncConflict dco_decode_sync_conflict(dynamic raw);

@protected SyncDirection dco_decode_sync_direction(dynamic raw);

@protected SyncHistoryEntry dco_decode_sync_history_entry(dynamic raw);

@protected SyncItem dco_decode_sync_item(dynamic raw);

@protected SyncResult dco_decode_sync_result(dynamic raw);

@protected SyncStatus dco_decode_sync_status(dynamic raw);

@protected SyncStatusInfo dco_decode_sync_status_info(dynamic raw);

@protected int dco_decode_u_32(dynamic raw);

@protected BigInt dco_decode_u_64(dynamic raw);

@protected int dco_decode_u_8(dynamic raw);

@protected void dco_decode_unit(dynamic raw);

@protected DateTime sse_decode_Chrono_Utc(SseDeserializer deserializer);

@protected String sse_decode_String(SseDeserializer deserializer);

@protected AuthResult sse_decode_auth_result(SseDeserializer deserializer);

@protected bool sse_decode_bool(SseDeserializer deserializer);

@protected DateTime sse_decode_box_autoadd_Chrono_Utc(SseDeserializer deserializer);

@protected ConflictInfo sse_decode_box_autoadd_conflict_info(SseDeserializer deserializer);

@protected PlatformInt64 sse_decode_box_autoadd_i_64(SseDeserializer deserializer);

@protected ServerInfo sse_decode_box_autoadd_server_info(SseDeserializer deserializer);

@protected SyncConfig sse_decode_box_autoadd_sync_config(SseDeserializer deserializer);

@protected ConflictInfo sse_decode_conflict_info(SseDeserializer deserializer);

@protected ConflictResolution sse_decode_conflict_resolution(SseDeserializer deserializer);

@protected ConflictType sse_decode_conflict_type(SseDeserializer deserializer);

@protected double sse_decode_f_32(SseDeserializer deserializer);

@protected int sse_decode_i_32(SseDeserializer deserializer);

@protected PlatformInt64 sse_decode_i_64(SseDeserializer deserializer);

@protected List<String> sse_decode_list_String(SseDeserializer deserializer);

@protected Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

@protected List<RemoteFolder> sse_decode_list_remote_folder(SseDeserializer deserializer);

@protected List<SyncConflict> sse_decode_list_sync_conflict(SseDeserializer deserializer);

@protected List<SyncHistoryEntry> sse_decode_list_sync_history_entry(SseDeserializer deserializer);

@protected List<SyncItem> sse_decode_list_sync_item(SseDeserializer deserializer);

@protected String? sse_decode_opt_String(SseDeserializer deserializer);

@protected DateTime? sse_decode_opt_box_autoadd_Chrono_Utc(SseDeserializer deserializer);

@protected PlatformInt64? sse_decode_opt_box_autoadd_i_64(SseDeserializer deserializer);

@protected ServerInfo? sse_decode_opt_box_autoadd_server_info(SseDeserializer deserializer);

@protected RemoteFolder sse_decode_remote_folder(SseDeserializer deserializer);

@protected ServerInfo sse_decode_server_info(SseDeserializer deserializer);

@protected SyncConfig sse_decode_sync_config(SseDeserializer deserializer);

@protected SyncConflict sse_decode_sync_conflict(SseDeserializer deserializer);

@protected SyncDirection sse_decode_sync_direction(SseDeserializer deserializer);

@protected SyncHistoryEntry sse_decode_sync_history_entry(SseDeserializer deserializer);

@protected SyncItem sse_decode_sync_item(SseDeserializer deserializer);

@protected SyncResult sse_decode_sync_result(SseDeserializer deserializer);

@protected SyncStatus sse_decode_sync_status(SseDeserializer deserializer);

@protected SyncStatusInfo sse_decode_sync_status_info(SseDeserializer deserializer);

@protected int sse_decode_u_32(SseDeserializer deserializer);

@protected BigInt sse_decode_u_64(SseDeserializer deserializer);

@protected int sse_decode_u_8(SseDeserializer deserializer);

@protected void sse_decode_unit(SseDeserializer deserializer);

@protected JSAny cst_encode_Chrono_Utc(DateTime raw){ // Codec=Cst (C-struct based), see doc to use other codecs
return cst_encode_i_64(BigInt.from(raw.millisecondsSinceEpoch)); }

@protected String cst_encode_String(String raw){ // Codec=Cst (C-struct based), see doc to use other codecs
return raw; }

@protected JSAny cst_encode_auth_result(AuthResult raw){ // Codec=Cst (C-struct based), see doc to use other codecs
return [cst_encode_bool(raw.success),cst_encode_String(raw.userId),cst_encode_String(raw.username),cst_encode_server_info(raw.serverInfo),cst_encode_String(raw.accessToken)].jsify()!; }

@protected JSAny cst_encode_box_autoadd_Chrono_Utc(DateTime raw){ // Codec=Cst (C-struct based), see doc to use other codecs
return cst_encode_Chrono_Utc(raw); }

@protected JSAny cst_encode_box_autoadd_conflict_info(ConflictInfo raw){ // Codec=Cst (C-struct based), see doc to use other codecs
return cst_encode_conflict_info(raw); }

@protected JSAny cst_encode_box_autoadd_i_64(PlatformInt64 raw){ // Codec=Cst (C-struct based), see doc to use other codecs
return cst_encode_i_64(raw); }

@protected JSAny cst_encode_box_autoadd_server_info(ServerInfo raw){ // Codec=Cst (C-struct based), see doc to use other codecs
return cst_encode_server_info(raw); }

@protected JSAny cst_encode_box_autoadd_sync_config(SyncConfig raw){ // Codec=Cst (C-struct based), see doc to use other codecs
return cst_encode_sync_config(raw); }

@protected JSAny cst_encode_conflict_info(ConflictInfo raw){ // Codec=Cst (C-struct based), see doc to use other codecs
return [cst_encode_conflict_type(raw.conflictType),cst_encode_Chrono_Utc(raw.detectedAt)].jsify()!; }

@protected JSAny cst_encode_i_64(PlatformInt64 raw){ // Codec=Cst (C-struct based), see doc to use other codecs
return castNativeBigInt(raw); }

@protected JSAny cst_encode_list_String(List<String> raw){ // Codec=Cst (C-struct based), see doc to use other codecs
return raw.map(cst_encode_String).toList().jsify()!; }

@protected JSAny cst_encode_list_prim_u_8_strict(Uint8List raw){ // Codec=Cst (C-struct based), see doc to use other codecs
return raw.jsify()!; }

@protected JSAny cst_encode_list_remote_folder(List<RemoteFolder> raw){ // Codec=Cst (C-struct based), see doc to use other codecs
return raw.map(cst_encode_remote_folder).toList().jsify()!; }

@protected JSAny cst_encode_list_sync_conflict(List<SyncConflict> raw){ // Codec=Cst (C-struct based), see doc to use other codecs
return raw.map(cst_encode_sync_conflict).toList().jsify()!; }

@protected JSAny cst_encode_list_sync_history_entry(List<SyncHistoryEntry> raw){ // Codec=Cst (C-struct based), see doc to use other codecs
return raw.map(cst_encode_sync_history_entry).toList().jsify()!; }

@protected JSAny cst_encode_list_sync_item(List<SyncItem> raw){ // Codec=Cst (C-struct based), see doc to use other codecs
return raw.map(cst_encode_sync_item).toList().jsify()!; }

@protected String? cst_encode_opt_String(String? raw){ // Codec=Cst (C-struct based), see doc to use other codecs
return raw == null ? null : cst_encode_String(raw); }

@protected JSAny? cst_encode_opt_box_autoadd_Chrono_Utc(DateTime? raw){ // Codec=Cst (C-struct based), see doc to use other codecs
return raw == null ? null : cst_encode_box_autoadd_Chrono_Utc(raw); }

@protected JSAny? cst_encode_opt_box_autoadd_i_64(PlatformInt64? raw){ // Codec=Cst (C-struct based), see doc to use other codecs
return raw == null ? null : cst_encode_box_autoadd_i_64(raw); }

@protected JSAny? cst_encode_opt_box_autoadd_server_info(ServerInfo? raw){ // Codec=Cst (C-struct based), see doc to use other codecs
return raw == null ? null : cst_encode_box_autoadd_server_info(raw); }

@protected JSAny cst_encode_remote_folder(RemoteFolder raw){ // Codec=Cst (C-struct based), see doc to use other codecs
return [cst_encode_String(raw.id),cst_encode_String(raw.name),cst_encode_String(raw.path),cst_encode_u_64(raw.sizeBytes),cst_encode_u_32(raw.itemCount),cst_encode_bool(raw.isSelected)].jsify()!; }

@protected JSAny cst_encode_server_info(ServerInfo raw){ // Codec=Cst (C-struct based), see doc to use other codecs
return [cst_encode_String(raw.url),cst_encode_String(raw.version),cst_encode_String(raw.name),cst_encode_String(raw.webdavUrl),cst_encode_u_64(raw.quotaTotal),cst_encode_u_64(raw.quotaUsed),cst_encode_bool(raw.supportsDeltaSync),cst_encode_bool(raw.supportsChunkedUpload)].jsify()!; }

@protected JSAny cst_encode_sync_config(SyncConfig raw){ // Codec=Cst (C-struct based), see doc to use other codecs
return [cst_encode_String(raw.syncFolder),cst_encode_String(raw.databasePath),cst_encode_u_32(raw.syncIntervalSeconds),cst_encode_u_32(raw.maxUploadSpeedKbps),cst_encode_u_32(raw.maxDownloadSpeedKbps),cst_encode_bool(raw.deltaSyncEnabled),cst_encode_u_64(raw.deltaSyncMinSize),cst_encode_bool(raw.pauseOnMetered),cst_encode_bool(raw.wifiOnly),cst_encode_bool(raw.watchFilesystem),cst_encode_list_String(raw.ignorePatterns),cst_encode_bool(raw.notificationsEnabled),cst_encode_bool(raw.launchAtStartup),cst_encode_bool(raw.minimizeToTray)].jsify()!; }

@protected JSAny cst_encode_sync_conflict(SyncConflict raw){ // Codec=Cst (C-struct based), see doc to use other codecs
return [cst_encode_String(raw.id),cst_encode_String(raw.itemPath),cst_encode_i_64(raw.localModified),cst_encode_i_64(raw.remoteModified),cst_encode_u_64(raw.localSize),cst_encode_u_64(raw.remoteSize),cst_encode_conflict_type(raw.conflictType)].jsify()!; }

@protected JSAny cst_encode_sync_history_entry(SyncHistoryEntry raw){ // Codec=Cst (C-struct based), see doc to use other codecs
return [cst_encode_String(raw.id),cst_encode_i_64(raw.timestamp),cst_encode_String(raw.operation),cst_encode_String(raw.itemPath),cst_encode_String(raw.direction),cst_encode_String(raw.status),cst_encode_opt_String(raw.errorMessage)].jsify()!; }

@protected JSAny cst_encode_sync_item(SyncItem raw){ // Codec=Cst (C-struct based), see doc to use other codecs
return [cst_encode_String(raw.id),cst_encode_String(raw.path),cst_encode_String(raw.name),cst_encode_bool(raw.isDirectory),cst_encode_u_64(raw.size),cst_encode_opt_String(raw.contentHash),cst_encode_opt_box_autoadd_Chrono_Utc(raw.localModified),cst_encode_opt_box_autoadd_Chrono_Utc(raw.remoteModified),cst_encode_sync_status(raw.status),cst_encode_sync_direction(raw.direction),cst_encode_opt_String(raw.etag),cst_encode_opt_String(raw.mimeType)].jsify()!; }

@protected JSAny cst_encode_sync_result(SyncResult raw){ // Codec=Cst (C-struct based), see doc to use other codecs
return [cst_encode_bool(raw.success),cst_encode_u_32(raw.itemsUploaded),cst_encode_u_32(raw.itemsDownloaded),cst_encode_u_32(raw.itemsDeleted),cst_encode_u_32(raw.conflicts),cst_encode_list_String(raw.errors),cst_encode_u_64(raw.durationMs)].jsify()!; }

@protected JSAny cst_encode_sync_status(SyncStatus raw){ // Codec=Cst (C-struct based), see doc to use other codecs
if (raw is SyncStatus_Synced) {
            return [0 ].jsify()!;
        }
if (raw is SyncStatus_Pending) {
            return [1 ].jsify()!;
        }
if (raw is SyncStatus_Syncing) {
            return [2 ].jsify()!;
        }
if (raw is SyncStatus_Conflict) {
            return [3 ,cst_encode_box_autoadd_conflict_info(raw.field0)].jsify()!;
        }
if (raw is SyncStatus_Error) {
            return [4 ,cst_encode_String(raw.field0)].jsify()!;
        }
if (raw is SyncStatus_Ignored) {
            return [5 ].jsify()!;
        }

                throw Exception('unreachable'); }

@protected JSAny cst_encode_sync_status_info(SyncStatusInfo raw){ // Codec=Cst (C-struct based), see doc to use other codecs
return [cst_encode_bool(raw.isSyncing),cst_encode_opt_String(raw.currentOperation),cst_encode_f_32(raw.progressPercent),cst_encode_u_32(raw.itemsSynced),cst_encode_u_32(raw.itemsTotal),cst_encode_opt_box_autoadd_i_64(raw.lastSyncTime),cst_encode_opt_box_autoadd_i_64(raw.nextSyncTime)].jsify()!; }

@protected JSAny cst_encode_u_64(BigInt raw){ // Codec=Cst (C-struct based), see doc to use other codecs
return castNativeBigInt(raw); }

@protected bool cst_encode_bool(bool raw);

@protected int cst_encode_conflict_resolution(ConflictResolution raw);

@protected int cst_encode_conflict_type(ConflictType raw);

@protected double cst_encode_f_32(double raw);

@protected int cst_encode_i_32(int raw);

@protected int cst_encode_sync_direction(SyncDirection raw);

@protected int cst_encode_u_32(int raw);

@protected int cst_encode_u_8(int raw);

@protected void cst_encode_unit(void raw);

@protected void sse_encode_Chrono_Utc(DateTime self, SseSerializer serializer);

@protected void sse_encode_String(String self, SseSerializer serializer);

@protected void sse_encode_auth_result(AuthResult self, SseSerializer serializer);

@protected void sse_encode_bool(bool self, SseSerializer serializer);

@protected void sse_encode_box_autoadd_Chrono_Utc(DateTime self, SseSerializer serializer);

@protected void sse_encode_box_autoadd_conflict_info(ConflictInfo self, SseSerializer serializer);

@protected void sse_encode_box_autoadd_i_64(PlatformInt64 self, SseSerializer serializer);

@protected void sse_encode_box_autoadd_server_info(ServerInfo self, SseSerializer serializer);

@protected void sse_encode_box_autoadd_sync_config(SyncConfig self, SseSerializer serializer);

@protected void sse_encode_conflict_info(ConflictInfo self, SseSerializer serializer);

@protected void sse_encode_conflict_resolution(ConflictResolution self, SseSerializer serializer);

@protected void sse_encode_conflict_type(ConflictType self, SseSerializer serializer);

@protected void sse_encode_f_32(double self, SseSerializer serializer);

@protected void sse_encode_i_32(int self, SseSerializer serializer);

@protected void sse_encode_i_64(PlatformInt64 self, SseSerializer serializer);

@protected void sse_encode_list_String(List<String> self, SseSerializer serializer);

@protected void sse_encode_list_prim_u_8_strict(Uint8List self, SseSerializer serializer);

@protected void sse_encode_list_remote_folder(List<RemoteFolder> self, SseSerializer serializer);

@protected void sse_encode_list_sync_conflict(List<SyncConflict> self, SseSerializer serializer);

@protected void sse_encode_list_sync_history_entry(List<SyncHistoryEntry> self, SseSerializer serializer);

@protected void sse_encode_list_sync_item(List<SyncItem> self, SseSerializer serializer);

@protected void sse_encode_opt_String(String? self, SseSerializer serializer);

@protected void sse_encode_opt_box_autoadd_Chrono_Utc(DateTime? self, SseSerializer serializer);

@protected void sse_encode_opt_box_autoadd_i_64(PlatformInt64? self, SseSerializer serializer);

@protected void sse_encode_opt_box_autoadd_server_info(ServerInfo? self, SseSerializer serializer);

@protected void sse_encode_remote_folder(RemoteFolder self, SseSerializer serializer);

@protected void sse_encode_server_info(ServerInfo self, SseSerializer serializer);

@protected void sse_encode_sync_config(SyncConfig self, SseSerializer serializer);

@protected void sse_encode_sync_conflict(SyncConflict self, SseSerializer serializer);

@protected void sse_encode_sync_direction(SyncDirection self, SseSerializer serializer);

@protected void sse_encode_sync_history_entry(SyncHistoryEntry self, SseSerializer serializer);

@protected void sse_encode_sync_item(SyncItem self, SseSerializer serializer);

@protected void sse_encode_sync_result(SyncResult self, SseSerializer serializer);

@protected void sse_encode_sync_status(SyncStatus self, SseSerializer serializer);

@protected void sse_encode_sync_status_info(SyncStatusInfo self, SseSerializer serializer);

@protected void sse_encode_u_32(int self, SseSerializer serializer);

@protected void sse_encode_u_64(BigInt self, SseSerializer serializer);

@protected void sse_encode_u_8(int self, SseSerializer serializer);

@protected void sse_encode_unit(void self, SseSerializer serializer);
                }
                


// Section: wire_class

class RustLibWire implements BaseWire {
            RustLibWire.fromExternalLibrary(ExternalLibrary lib);

            void wire__crate__api__oxicloud__get_config(NativePortType port_) => wasmModule.wire__crate__api__oxicloud__get_config(port_);

void wire__crate__api__oxicloud__get_conflicts(NativePortType port_) => wasmModule.wire__crate__api__oxicloud__get_conflicts(port_);

void wire__crate__api__oxicloud__get_pending_items(NativePortType port_) => wasmModule.wire__crate__api__oxicloud__get_pending_items(port_);

void wire__crate__api__oxicloud__get_remote_folders(NativePortType port_) => wasmModule.wire__crate__api__oxicloud__get_remote_folders(port_);

void wire__crate__api__oxicloud__get_server_info(NativePortType port_) => wasmModule.wire__crate__api__oxicloud__get_server_info(port_);

void wire__crate__api__oxicloud__get_sync_folders(NativePortType port_) => wasmModule.wire__crate__api__oxicloud__get_sync_folders(port_);

void wire__crate__api__oxicloud__get_sync_history(NativePortType port_,int limit) => wasmModule.wire__crate__api__oxicloud__get_sync_history(port_,limit);

void wire__crate__api__oxicloud__get_sync_status(NativePortType port_) => wasmModule.wire__crate__api__oxicloud__get_sync_status(port_);

JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */ wire__crate__api__simple__greet(String name) => wasmModule.wire__crate__api__simple__greet(name);

void wire__crate__api__simple__init_app(NativePortType port_) => wasmModule.wire__crate__api__simple__init_app(port_);

void wire__crate__api__oxicloud__initialize(NativePortType port_,JSAny config) => wasmModule.wire__crate__api__oxicloud__initialize(port_,config);

void wire__crate__api__oxicloud__is_logged_in(NativePortType port_) => wasmModule.wire__crate__api__oxicloud__is_logged_in(port_);

void wire__crate__api__oxicloud__login(NativePortType port_,String server_url,String username,String password) => wasmModule.wire__crate__api__oxicloud__login(port_,server_url,username,password);

void wire__crate__api__oxicloud__logout(NativePortType port_) => wasmModule.wire__crate__api__oxicloud__logout(port_);

void wire__crate__api__oxicloud__resolve_conflict(NativePortType port_,String conflict_id,int resolution) => wasmModule.wire__crate__api__oxicloud__resolve_conflict(port_,conflict_id,resolution);

void wire__crate__api__oxicloud__set_sync_folders(NativePortType port_,JSAny folder_ids) => wasmModule.wire__crate__api__oxicloud__set_sync_folders(port_,folder_ids);

void wire__crate__api__oxicloud__shutdown(NativePortType port_) => wasmModule.wire__crate__api__oxicloud__shutdown(port_);

void wire__crate__api__oxicloud__start_sync(NativePortType port_) => wasmModule.wire__crate__api__oxicloud__start_sync(port_);

void wire__crate__api__oxicloud__stop_sync(NativePortType port_) => wasmModule.wire__crate__api__oxicloud__stop_sync(port_);

void wire__crate__api__oxicloud__sync_now(NativePortType port_) => wasmModule.wire__crate__api__oxicloud__sync_now(port_);

void wire__crate__api__oxicloud__update_config(NativePortType port_,JSAny config) => wasmModule.wire__crate__api__oxicloud__update_config(port_,config);
        }
        @JS('wasm_bindgen') external RustLibWasmModule get wasmModule;

        @JS() @anonymous extension type RustLibWasmModule._(JSObject _) implements JSObject {
            external void wire__crate__api__oxicloud__get_config(NativePortType port_);

external void wire__crate__api__oxicloud__get_conflicts(NativePortType port_);

external void wire__crate__api__oxicloud__get_pending_items(NativePortType port_);

external void wire__crate__api__oxicloud__get_remote_folders(NativePortType port_);

external void wire__crate__api__oxicloud__get_server_info(NativePortType port_);

external void wire__crate__api__oxicloud__get_sync_folders(NativePortType port_);

external void wire__crate__api__oxicloud__get_sync_history(NativePortType port_,int limit);

external void wire__crate__api__oxicloud__get_sync_status(NativePortType port_);

external JSAny? /* flutter_rust_bridge::for_generated::WireSyncRust2DartDco */ wire__crate__api__simple__greet(String name);

external void wire__crate__api__simple__init_app(NativePortType port_);

external void wire__crate__api__oxicloud__initialize(NativePortType port_,JSAny config);

external void wire__crate__api__oxicloud__is_logged_in(NativePortType port_);

external void wire__crate__api__oxicloud__login(NativePortType port_,String server_url,String username,String password);

external void wire__crate__api__oxicloud__logout(NativePortType port_);

external void wire__crate__api__oxicloud__resolve_conflict(NativePortType port_,String conflict_id,int resolution);

external void wire__crate__api__oxicloud__set_sync_folders(NativePortType port_,JSAny folder_ids);

external void wire__crate__api__oxicloud__shutdown(NativePortType port_);

external void wire__crate__api__oxicloud__start_sync(NativePortType port_);

external void wire__crate__api__oxicloud__stop_sync(NativePortType port_);

external void wire__crate__api__oxicloud__sync_now(NativePortType port_);

external void wire__crate__api__oxicloud__update_config(NativePortType port_,JSAny config);
        }
        