// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Server information
class ServerInfo {
  /// Server URL
  final String url;

  /// Server version
  final String version;

  /// Server name
  final String name;

  /// WebDAV endpoint
  final String webdavUrl;

  /// User storage quota (bytes)
  final BigInt quotaTotal;

  /// Used storage (bytes)
  final BigInt quotaUsed;

  /// Whether the server supports delta sync
  final bool supportsDeltaSync;

  /// Whether the server supports chunked uploads
  final bool supportsChunkedUpload;

  const ServerInfo({
    required this.url,
    required this.version,
    required this.name,
    required this.webdavUrl,
    required this.quotaTotal,
    required this.quotaUsed,
    required this.supportsDeltaSync,
    required this.supportsChunkedUpload,
  });

  @override
  int get hashCode =>
      url.hashCode ^
      version.hashCode ^
      name.hashCode ^
      webdavUrl.hashCode ^
      quotaTotal.hashCode ^
      quotaUsed.hashCode ^
      supportsDeltaSync.hashCode ^
      supportsChunkedUpload.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ServerInfo &&
          runtimeType == other.runtimeType &&
          url == other.url &&
          version == other.version &&
          name == other.name &&
          webdavUrl == other.webdavUrl &&
          quotaTotal == other.quotaTotal &&
          quotaUsed == other.quotaUsed &&
          supportsDeltaSync == other.supportsDeltaSync &&
          supportsChunkedUpload == other.supportsChunkedUpload;
}
