// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Sync engine configuration
class SyncConfig {
  /// Path to local sync folder
  final String syncFolder;

  /// Path to SQLite database file
  final String databasePath;

  /// Sync interval in seconds (0 = manual only)
  final int syncIntervalSeconds;

  /// Maximum upload speed in KB/s (0 = unlimited)
  final int maxUploadSpeedKbps;

  /// Maximum download speed in KB/s (0 = unlimited)
  final int maxDownloadSpeedKbps;

  /// Enable delta sync for large files
  final bool deltaSyncEnabled;

  /// Minimum file size for delta sync (bytes)
  final BigInt deltaSyncMinSize;

  /// Pause sync on metered connections
  final bool pauseOnMetered;

  /// Only sync on Wi-Fi (mobile)
  final bool wifiOnly;

  /// Enable file system watcher for instant sync
  final bool watchFilesystem;

  /// Ignore patterns (glob)
  final List<String> ignorePatterns;

  /// Show desktop notifications
  final bool notificationsEnabled;

  /// Launch on system startup
  final bool launchAtStartup;

  /// Minimize to tray on close (desktop)
  final bool minimizeToTray;

  const SyncConfig({
    required this.syncFolder,
    required this.databasePath,
    required this.syncIntervalSeconds,
    required this.maxUploadSpeedKbps,
    required this.maxDownloadSpeedKbps,
    required this.deltaSyncEnabled,
    required this.deltaSyncMinSize,
    required this.pauseOnMetered,
    required this.wifiOnly,
    required this.watchFilesystem,
    required this.ignorePatterns,
    required this.notificationsEnabled,
    required this.launchAtStartup,
    required this.minimizeToTray,
  });

  @override
  int get hashCode =>
      syncFolder.hashCode ^
      databasePath.hashCode ^
      syncIntervalSeconds.hashCode ^
      maxUploadSpeedKbps.hashCode ^
      maxDownloadSpeedKbps.hashCode ^
      deltaSyncEnabled.hashCode ^
      deltaSyncMinSize.hashCode ^
      pauseOnMetered.hashCode ^
      wifiOnly.hashCode ^
      watchFilesystem.hashCode ^
      ignorePatterns.hashCode ^
      notificationsEnabled.hashCode ^
      launchAtStartup.hashCode ^
      minimizeToTray.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncConfig &&
          runtimeType == other.runtimeType &&
          syncFolder == other.syncFolder &&
          databasePath == other.databasePath &&
          syncIntervalSeconds == other.syncIntervalSeconds &&
          maxUploadSpeedKbps == other.maxUploadSpeedKbps &&
          maxDownloadSpeedKbps == other.maxDownloadSpeedKbps &&
          deltaSyncEnabled == other.deltaSyncEnabled &&
          deltaSyncMinSize == other.deltaSyncMinSize &&
          pauseOnMetered == other.pauseOnMetered &&
          wifiOnly == other.wifiOnly &&
          watchFilesystem == other.watchFilesystem &&
          ignorePatterns == other.ignorePatterns &&
          notificationsEnabled == other.notificationsEnabled &&
          launchAtStartup == other.launchAtStartup &&
          minimizeToTray == other.minimizeToTray;
}
