// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
part 'sync_item.freezed.dart';

/// Conflict information
class ConflictInfo {
  final ConflictType conflictType;
  final DateTime detectedAt;

  const ConflictInfo({
    required this.conflictType,
    required this.detectedAt,
  });

  @override
  int get hashCode => conflictType.hashCode ^ detectedAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ConflictInfo &&
          runtimeType == other.runtimeType &&
          conflictType == other.conflictType &&
          detectedAt == other.detectedAt;
}

/// Conflict resolution strategy
enum ConflictResolution {
  /// Keep local version
  keepLocal,

  /// Keep remote version
  keepRemote,

  /// Keep both (rename local)
  keepBoth,

  /// Skip this item
  skip,
  ;
}

/// Type of conflict
enum ConflictType {
  /// Both local and remote were modified
  bothModified,

  /// Deleted locally but modified remotely
  deletedLocally,

  /// Modified locally but deleted remotely
  deletedRemotely,

  /// File vs folder type mismatch
  typeMismatch,
  ;
}

/// Sync direction
enum SyncDirection {
  /// Upload to server
  upload,

  /// Download from server
  download,

  /// No sync needed
  none,
  ;
}

/// Represents a syncable item (file or folder)
class SyncItem {
  /// Unique identifier
  final String id;

  /// Relative path from sync root
  final String path;

  /// File name
  final String name;

  /// Whether this is a directory
  final bool isDirectory;

  /// File size in bytes (0 for directories)
  final BigInt size;

  /// Content hash (for change detection)
  final String? contentHash;

  /// Local modification time
  final DateTime? localModified;

  /// Remote modification time
  final DateTime? remoteModified;

  /// Current sync status
  final SyncStatus status;

  /// Sync direction
  final SyncDirection direction;

  /// ETag from server (for efficient sync)
  final String? etag;

  /// MIME type
  final String? mimeType;

  const SyncItem({
    required this.id,
    required this.path,
    required this.name,
    required this.isDirectory,
    required this.size,
    this.contentHash,
    this.localModified,
    this.remoteModified,
    required this.status,
    required this.direction,
    this.etag,
    this.mimeType,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      path.hashCode ^
      name.hashCode ^
      isDirectory.hashCode ^
      size.hashCode ^
      contentHash.hashCode ^
      localModified.hashCode ^
      remoteModified.hashCode ^
      status.hashCode ^
      direction.hashCode ^
      etag.hashCode ^
      mimeType.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is SyncItem &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          path == other.path &&
          name == other.name &&
          isDirectory == other.isDirectory &&
          size == other.size &&
          contentHash == other.contentHash &&
          localModified == other.localModified &&
          remoteModified == other.remoteModified &&
          status == other.status &&
          direction == other.direction &&
          etag == other.etag &&
          mimeType == other.mimeType;
}

@freezed
sealed class SyncStatus with _$SyncStatus {
  const SyncStatus._();

  /// Item is in sync
  const factory SyncStatus.synced() = SyncStatus_Synced;

  /// Item needs to be synced
  const factory SyncStatus.pending() = SyncStatus_Pending;

  /// Item is currently being synced
  const factory SyncStatus.syncing() = SyncStatus_Syncing;

  /// Item has a conflict
  const factory SyncStatus.conflict(
    ConflictInfo field0,
  ) = SyncStatus_Conflict;

  /// Sync error occurred
  const factory SyncStatus.error(
    String field0,
  ) = SyncStatus_Error;

  /// Item is ignored
  const factory SyncStatus.ignored() = SyncStatus_Ignored;
}
