name: Android Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.29.1'
        channel: 'stable'
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Setup Flutter SDK path
      run: |
        echo "flutter.sdk=$FLUTTER_HOME" > android/local.properties
    
    - name: Clean build directory
      run: |
        rm -rf build/
        flutter clean
    
    - name: Build APK
      run: flutter build apk --release
    
    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: release-apk
        path: build/app/outputs/flutter-apk/app-release.apk 