name: Android Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.29.3'
        channel: 'stable'

    - name: Install dependencies
      run: flutter pub get

    - name: Setup Flutter SDK path
      run: |
        echo "flutter.sdk=${{ env.FLUTTER_ROOT }}" > android/local.properties
        echo "Contents of local.properties:"
        cat android/local.properties

    - name: Clean build directory
      run: |
        rm -rf build/
        flutter clean

    - name: Update Gradle settings for Flutter 3.29.3
      run: |
        # Comment out the deprecated plugin loader line in settings.gradle
        sed -i 's|apply from: "${flutterSdkPath}/packages/flutter_tools/gradle/app_plugin_loader.gradle"|// apply from: "${flutterSdkPath}/packages/flutter_tools/gradle/app_plugin_loader.gradle"|g' android/settings.gradle

        # Make sure we're using the new plugin system
        if ! grep -q "plugins {" android/app/build.gradle; then
          # If not using the new plugins block, add it
          sed -i '1s/^/plugins {\n    id "com.android.application"\n    id "kotlin-android"\n    id "dev.flutter.flutter-gradle-plugin"\n}\n\n/' android/app/build.gradle
        fi

        # Fix MainActivity.kt imports
        cat > android/app/src/main/kotlin/com/example/oxicloud_desktop/MainActivity.kt << 'EOF'
        package com.example.oxicloud_desktop

        import androidx.annotation.NonNull
        import io.flutter.embedding.android.FlutterActivity
        import io.flutter.embedding.engine.FlutterEngine
        import io.flutter.plugins.GeneratedPluginRegistrant

        class MainActivity: FlutterActivity() {
            override fun configureFlutterEngine(@NonNull flutterEngine: FlutterEngine) {
                GeneratedPluginRegistrant.registerWith(flutterEngine)
            }
        }
        EOF

    - name: Update Gradle version
      run: |
        # Update Gradle version to match the Android Gradle plugin version
        sed -i 's/distributionUrl=.*$/distributionUrl=https\\:\/\/services.gradle.org\/distributions\/gradle-8.4-all.zip/g' android/gradle/wrapper/gradle-wrapper.properties
        cat android/gradle/wrapper/gradle-wrapper.properties

    - name: Build APK
      run: flutter build apk --release

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: release-apk
        path: build/app/outputs/flutter-apk/app-release.apk