name: Build OxiCloud Desktop Client

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'
          channel: 'stable'
      - name: Install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y clang cmake ninja-build pkg-config libgtk-3-dev liblzma-dev libstdc++-12-dev
          sudo apt-get install -y libx11-dev libxrandr-dev libxi-dev libxinerama-dev libxcursor-dev libxfixes-dev
          sudo apt-get install -y libgl1-mesa-dev libgl2ps-dev libglu1-mesa-dev
          sudo apt-get install -y libxkbcommon-dev libxkbcommon-x11-dev
          sudo apt-get install -y libatk1.0-dev libcairo2-dev libpango1.0-dev
          sudo apt-get install -y libgdk-pixbuf2.0-dev
      - name: Build Linux
        run: |
          flutter clean
          flutter config --enable-linux-desktop
          flutter pub get
          dart run build_runner build --delete-conflicting-outputs
          flutter create --platforms=linux .
          cd linux
          export FLUTTER_ROOT=$(which flutter | xargs dirname | xargs dirname)
          export FLUTTER_ENGINE=$FLUTTER_ROOT/bin/cache/artifacts/engine
          export FLUTTER_CMAKE_DIR=$FLUTTER_ROOT/packages/flutter_tools/bin/cmake
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DFLUTTER_ROOT=$FLUTTER_ROOT -DFLUTTER_ENGINE=$FLUTTER_ENGINE -DFLUTTER_CMAKE_DIR=$FLUTTER_CMAKE_DIR
          cmake --build build
          cd ..
          flutter build linux

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'
          channel: 'stable'
      - name: Install CMake
        run: |
          choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'
      - name: Build Windows
        run: |
          flutter clean
          flutter config --enable-windows-desktop
          flutter pub get
          dart run build_runner build --delete-conflicting-outputs
          flutter create --platforms=windows .
          cd windows
          $env:FLUTTER_ROOT = (Get-Command flutter).Source | Split-Path -Parent | Split-Path -Parent
          $env:FLUTTER_ENGINE = "$env:FLUTTER_ROOT\bin\cache\artifacts\engine"
          $env:FLUTTER_CMAKE_DIR = "$env:FLUTTER_ROOT\packages\flutter_tools\bin\cmake"
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release -DFLUTTER_ROOT=$env:FLUTTER_ROOT -DFLUTTER_ENGINE=$env:FLUTTER_ENGINE -DFLUTTER_CMAKE_DIR=$env:FLUTTER_CMAKE_DIR
          cmake --build build
          cd ..
          flutter build windows

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'
          channel: 'stable'
      - name: Build macOS
        run: |
          flutter clean
          flutter config --enable-macos-desktop
          flutter pub get
          dart run build_runner build --delete-conflicting-outputs
          flutter create --platforms=macos .
          flutter build macos

  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'
          channel: 'stable'
      - uses: android-actions/setup-android@v3
      - name: Build Android
        run: |
          flutter clean
          flutter pub get
          dart run build_runner build --delete-conflicting-outputs
          flutter create --platforms=android .
          cd android
          ./gradlew clean
          cd ..
          flutter build apk --release

  build-ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.3'
          channel: 'stable'
      - name: Install CocoaPods
        run: |
          sudo gem install cocoapods
      - name: Build iOS
        run: |
          flutter clean
          flutter pub get
          dart run build_runner build --delete-conflicting-outputs
          flutter create --platforms=ios .
          cd ios
          pod install
          cd ..
          flutter build ios --release --no-codesign

  upload-artifacts:
    needs: [build-linux, build-windows, build-macos, build-android, build-ios]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Download Linux Artifact
        uses: actions/download-artifact@v3
        with:
          name: linux-build
          path: artifacts/linux
      - name: Download Windows Artifact
        uses: actions/download-artifact@v3
        with:
          name: windows-build
          path: artifacts/windows
      - name: Download macOS Artifact
        uses: actions/download-artifact@v3
        with:
          name: macos-build
          path: artifacts/macos
      - name: Download Android Artifact
        uses: actions/download-artifact@v3
        with:
          name: android-build
          path: artifacts/android
      - name: Download iOS Artifact
        uses: actions/download-artifact@v3
        with:
          name: ios-build
          path: artifacts/ios
      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            artifacts/linux/*
            artifacts/windows/*
            artifacts/macos/*
            artifacts/android/*
            artifacts/ios/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 