name: iOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.29.1'
        channel: 'stable'
        cache: true

    - name: Install dependencies
      run: flutter pub get

    - name: Clean build directory
      run: |
        rm -rf build/
        rm -rf ios/Pods/
        rm -rf ios/.symlinks/
        rm -rf ios/Flutter/Flutter.framework
        rm -rf ios/Flutter/Flutter.podspec
        rm -rf ios/Flutter/ephemeral/

    - name: Setup Flutter
      run: |
        flutter clean
        flutter pub get
        flutter pub run build_runner build --delete-conflicting-outputs

    - name: Create required asset directories
      run: |
        mkdir -p assets/images
        mkdir -p assets/icons
        mkdir -p assets/fonts
        touch assets/images/.gitkeep
        touch assets/icons/.gitkeep
        touch assets/fonts/.gitkeep

    - name: Setup CocoaPods
      run: |
        cd ios
        pod deintegrate
        pod cache clean --all
        pod setup
        pod install
        cd ..

    - name: Build iOS
      run: flutter build ios --release --no-codesign

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ios-build
        path: build/ios/iphoneos/Runner.app
        if-no-files-found: error 