name: Linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.29.1'
        channel: 'stable'
        cache: true

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev
        flutter pub get

    - name: Clean build directory
      run: |
        rm -rf build/
        rm -rf linux/build/

    - name: Setup Flutter
      run: |
        flutter clean
        flutter pub get
        flutter pub run build_runner build --delete-conflicting-outputs

    - name: Create required asset directories
      run: |
        mkdir -p assets/images
        mkdir -p assets/icons
        mkdir -p assets/fonts
        touch assets/images/.gitkeep
        touch assets/icons/.gitkeep
        touch assets/fonts/.gitkeep

    - name: Build Linux
      run: flutter build linux --release

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: linux-build
        path: build/linux/x64/release/bundle
        if-no-files-found: error 