name: macOS Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.29.1'
        channel: 'stable'
    
    - name: Install dependencies
      run: |
        flutter pub get
        flutter precache --macos
    
    - name: Setup Flutter for macOS
      run: |
        flutter config --enable-macos-desktop
        flutter create --platforms=macos .
        flutter pub get
        
        # Generate ephemeral Flutter directory for macOS
        flutter build macos --debug || true
        
        # Regenerate Flutter macOS files
        cd macos
        pod install --repo-update
        cd ..
        
        # Run build_runner if needed (for code generation)
        flutter pub run build_runner build --delete-conflicting-outputs
    
    - name: Build macOS
      run: flutter build macos --release
    
    - name: Upload macOS Artifact
      uses: actions/upload-artifact@v4
      with:
        name: macos-build
        path: build/macos/Build/Products/Release/