name: macOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.29.1'
        channel: 'stable'
        cache: true

    - name: Install dependencies
      run: flutter pub get

    - name: Clean build directory
      run: |
        rm -rf build/
        rm -rf macos/Pods/
        rm -rf .symlinks/
        rm -rf Flutter/ephemeral/
        rm -rf Flutter/Flutter.framework
        rm -rf Flutter/Flutter.podspec

    - name: Setup Flutter
      run: |
        flutter clean
        flutter pub get
        cd macos
        pod deintegrate
        pod cache clean --all
        pod setup
        pod install
        cd ..

    - name: Build macOS
      run: flutter build macos --release

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: macos-build
        path: build/macos/Build/Products/Release/oxicloud_desktop.app
        if-no-files-found: error 