name: macOS Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.29.3'
        channel: 'stable'

    - name: Install dependencies
      run: |
        flutter pub get
        flutter precache --macos

    - name: Setup Flutter for macOS
      run: |
        flutter config --enable-macos-desktop
        flutter create --platforms=macos .
        flutter pub get

    - name: Modify macOS Podfile
      run: |
        # Modify the problematic line in the Podfile - macOS sed requires different syntax
        sed -i '' "s|require File.expand_path(.*Flutter.podspec.*)|# Line commented for CI build|" macos/Podfile

        # Create directory structure
        mkdir -p macos/Flutter/ephemeral

        # Create minimal Flutter.podspec file
        cat > macos/Flutter/ephemeral/Flutter.podspec << 'EOF'
        # This podspec is only used as a local source!
        Pod::Spec.new do |s|
          s.name             = 'Flutter'
          s.version          = '1.0.0'
          s.summary          = 'High-performance, high-fidelity mobile apps.'
          s.description      = <<-DESC
        Flutter provides an easy and productive way to build and deploy high-performance mobile apps for Android and iOS.
                               DESC
          s.homepage         = 'https://flutter.dev'
          s.license          = { :type => 'MIT' }
          s.author           = { 'Flutter Dev Team' => 'flutter-dev@googlegroups.com' }
          s.source           = { :git => 'https://github.com/flutter/engine', :tag => s.version.to_s }
          s.osx.deployment_target = '10.14'
          s.vendored_frameworks = 'App.framework', 'FlutterMacOS.framework'
          s.xcconfig = { 'ENABLE_BITCODE' => 'NO' }
        end
        EOF

        # Create Flutter-Generated.xcconfig if it doesn't exist
        if [ ! -f macos/Flutter/ephemeral/Flutter-Generated.xcconfig ]; then
          echo "FLUTTER_ROOT=$FLUTTER_ROOT" > macos/Flutter/ephemeral/Flutter-Generated.xcconfig
          echo "FLUTTER_APPLICATION_PATH=$(pwd)" >> macos/Flutter/ephemeral/Flutter-Generated.xcconfig
        fi

    - name: Generate Flutter macOS files
      run: |
        # Pre-build to generate Flutter files
        flutter build macos --debug --no-codesign || true

        # Apply workarounds for pod issues
        cd macos

        # Try with custom pod command that ignores missing podspec
        pod install --repo-update || (echo "Pod install failed, trying alternative approach" &&
          (mkdir -p Flutter/ephemeral/FlutterMacOS.framework &&
           mkdir -p Flutter/ephemeral/App.framework &&
           pod install --repo-update --verbose))

        cd ..

    - name: Build macOS
      run: flutter build macos --release

    - name: Upload macOS Artifact
      uses: actions/upload-artifact@v4
      with:
        name: macos-build
        path: build/macos/Build/Products/Release/