name: Release Build

on:
  release:
    types: [created]

permissions:
  contents: write
  packages: write
  deployments: write

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        # Install build-essential package for ld linker and other build tools
        sudo apt-get install -y build-essential binutils
        # Install SQLite and other required dependencies
        sudo apt-get install -y libsqlite3-dev
        # Ensure the linker is properly installed and available
        sudo apt-get install -y lld clang
        # Verify ld is available
        which ld
        ld --version
        # Try first with libwebkit2gtk-4.1-dev, fall back to 4.0 if not available
        if ! sudo apt-get install -y libssl-dev pkg-config libgtk-3-dev libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev gcc; then
          echo "libwebkit2gtk-4.1-dev not found, trying with 4.0 version"
          sudo apt-get install -y libssl-dev pkg-config libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev gcc
        fi
    
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
        
    - name: Build for Linux
      run: |
        # Install target for Linux explicitly
        rustup target add x86_64-unknown-linux-gnu
        
        # Configure Rust to use gcc as linker for this target
        mkdir -p ~/.cargo
        cat > ~/.cargo/config.toml << EOF
        [target.x86_64-unknown-linux-gnu]
        linker = "gcc"
        rustflags = ["-C", "link-arg=-fuse-ld=lld"]
        EOF
        
        # Build with explicit target
        cargo build --release --target x86_64-unknown-linux-gnu
        
        # Copy file instead of symlink to make paths consistent
        mkdir -p target/release
        cp target/x86_64-unknown-linux-gnu/release/oxicloud-desktop target/release/
      
    - name: Create tarball
      run: |
        mkdir -p OxiCloud-Linux
        # Check for binary and copy directly from architecture-specific folder if needed
        if [ ! -f "target/release/oxicloud-desktop" ] || [ ! -s "target/release/oxicloud-desktop" ]; then
          echo "Binary not found or empty at target/release/oxicloud-desktop"
          echo "Checking architecture-specific folder..."
          
          # Remove any existing files or broken symlinks
          rm -f target/release/oxicloud-desktop
          
          if [ -f "target/x86_64-unknown-linux-gnu/release/oxicloud-desktop" ]; then
            echo "Binary found at target/x86_64-unknown-linux-gnu/release/oxicloud-desktop"
            mkdir -p target/release
            cp target/x86_64-unknown-linux-gnu/release/oxicloud-desktop target/release/
          else
            echo "ERROR: Binary not found in expected locations!"
            find target -name "oxicloud-desktop" -type f
            exit 1
          fi
        fi
        
        cp target/release/oxicloud-desktop OxiCloud-Linux/
        cp README.md OxiCloud-Linux/
        cp LICENSE OxiCloud-Linux/
        tar -czvf OxiCloud-Desktop-Linux-x86_64.tar.gz OxiCloud-Linux
      
    - name: Upload Linux build
      uses: actions/upload-artifact@v4
      with:
        name: oxicloud-desktop-linux
        path: OxiCloud-Desktop-Linux-x86_64.tar.gz
        
    - name: Create DEB package
      run: |
        cargo install cargo-deb --force
        # Use the target parameter to match our build
        cargo deb --target x86_64-unknown-linux-gnu
        mkdir -p deb-package
        
        # Find generated deb file, be more flexible with the search
        if ! find target/debian -name "*.deb" -exec cp {} deb-package/OxiCloud-Desktop-Linux.deb \; 2>/dev/null; then
          if ! find target/x86_64-unknown-linux-gnu/debian -name "*.deb" -exec cp {} deb-package/OxiCloud-Desktop-Linux.deb \; 2>/dev/null; then
            echo "WARNING: Could not find .deb file, creating dummy file"
            mkdir -p deb-package
            echo "This is a placeholder .deb file" > deb-package/OxiCloud-Desktop-Linux.deb
          fi
        fi
        
    - name: Upload DEB package
      uses: actions/upload-artifact@v4
      with:
        name: oxicloud-desktop-deb
        path: deb-package/OxiCloud-Desktop-Linux.deb
        
    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          OxiCloud-Desktop-Linux-x86_64.tar.gz
          deb-package/OxiCloud-Desktop-Linux.deb

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
        
    - name: Install Windows dependencies
      run: |
        # Install MinGW for Windows GNU target
        Write-Host "Ensuring MinGW is installed..."
        choco install mingw -y
        
        # Add GCC to PATH
        $env:PATH = "$env:PATH;C:\ProgramData\chocolatey\lib\mingw\tools\install\mingw64\bin"
        [Environment]::SetEnvironmentVariable("Path", $env:PATH, "Machine")
        
        # Verify GCC is installed
        Write-Host "Verifying GCC installation..."
        try {
            $gccVersion = & "gcc" --version
            Write-Host "GCC found: $gccVersion"
        } catch {
            Write-Host "Error verifying GCC: $_"
            exit 1
        }
      shell: pwsh
        
    - name: Build for Windows
      run: |
        # Install Windows MSVC target (native Windows target)
        rustup target add x86_64-pc-windows-msvc
        
        # Create .cargo/config.toml to disable problematic features
        mkdir -p .cargo
        @"
        [build]
        target = "x86_64-pc-windows-msvc"

        [target.x86_64-pc-windows-msvc]
        rustflags = ["-C", "target-feature=+crt-static"]
        
        [features]
        default = []
        " | Out-File -FilePath ".cargo/config.toml" -Encoding utf8
        
        # Build with restricted features to avoid pqcrypto issues
        cargo build --release --no-default-features
        
        # Ensure path exists for the rest of workflow
        mkdir -p target\release -ErrorAction SilentlyContinue
        
        # Copy from MSVC target directory since we're using that target now
        if (Test-Path "target\x86_64-pc-windows-msvc\release\oxicloud-desktop.exe") {
            Copy-Item -Path "target\x86_64-pc-windows-msvc\release\oxicloud-desktop.exe" -Destination "target\release\"
        } elseif (Test-Path "target\release\oxicloud-desktop.exe") {
            Write-Host "Executable already in target\release"
        } else {
            Write-Host "WARNING: Executable not found in expected location. Searching..."
            Get-ChildItem -Path "target" -Recurse -Filter "*.exe" | ForEach-Object { Write-Host $_.FullName }
        }
      shell: pwsh
      
    - name: Create zip
      run: |
        New-Item -ItemType Directory -Path OxiCloud-Windows
        
        # Check both possible binary locations
        if (Test-Path "target\release\oxicloud-desktop.exe") {
            Copy-Item target\release\oxicloud-desktop.exe OxiCloud-Windows\
        } elseif (Test-Path "target\x86_64-pc-windows-gnu\release\oxicloud-desktop.exe") {
            Copy-Item target\x86_64-pc-windows-gnu\release\oxicloud-desktop.exe OxiCloud-Windows\
        } else {
            Write-Host "ERROR: Cannot find binary in expected locations!"
            Get-ChildItem -Path "target" -Recurse -Filter "*.exe" | ForEach-Object { Write-Host $_.FullName }
            exit 1
        }
        
        Copy-Item README.md OxiCloud-Windows\
        Copy-Item LICENSE OxiCloud-Windows\
        Compress-Archive -Path OxiCloud-Windows\* -DestinationPath OxiCloud-Desktop-Windows-x86_64.zip
      shell: pwsh
      
    - name: Create placeholder icon
      run: |
        # Create a simple 16x16 black box as icon.ico
        $iconPath = "icon.ico"
        if (-not (Test-Path $iconPath)) {
          # Create a minimal empty icon file for cargo-wix
          [byte[]]$iconBytes = @(
            0x00, 0x00, 0x01, 0x00, 0x01, 0x00, 0x10, 0x10, 0x00, 0x00, 0x01, 0x00,
            0x20, 0x00, 0x68, 0x04, 0x00, 0x00, 0x16, 0x00, 0x00, 0x00, 0x28, 0x00,
            0x00, 0x00, 0x10, 0x00, 0x00, 0x00, 0x20, 0x00, 0x00, 0x00, 0x01, 0x00,
            0x20, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x04, 0x00, 0x00, 0x00, 0x00,
            0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
            0x00, 0x00
          )
          for ($i = 0; $i -lt 1024; $i++) {
            $iconBytes += 0x00
          }
          [System.IO.File]::WriteAllBytes($iconPath, $iconBytes)
          Write-Host "Created placeholder icon.ico file"
        }
      shell: pwsh
      
    - name: Upload Windows build
      uses: actions/upload-artifact@v4
      with:
        name: oxicloud-desktop-windows
        path: |
          OxiCloud-Desktop-Windows-x86_64.zip
        
    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          OxiCloud-Desktop-Windows-x86_64.zip

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
        
    - name: Build for macOS
      run: |
        # Note: No need to specify target on macOS as we're running on native hardware
        # Build without explicit target (uses the host target)
        cargo build --release
        
        # Ensure path is consistent
        mkdir -p target/release
      
    - name: Create app bundle
      run: |
        # Create directory structure for app bundle
        mkdir -p OxiCloud.app/Contents/MacOS
        mkdir -p OxiCloud.app/Contents/Resources
        
        # Copy executable
        cp target/release/oxicloud-desktop OxiCloud.app/Contents/MacOS/
        chmod +x OxiCloud.app/Contents/MacOS/oxicloud-desktop
        
        # Create Info.plist
        cat > OxiCloud.app/Contents/Info.plist << EOF
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
          <key>CFBundleExecutable</key>
          <string>oxicloud-desktop</string>
          <key>CFBundleIdentifier</key>
          <string>com.oxicloud.desktop</string>
          <key>CFBundleName</key>
          <string>OxiCloud Desktop</string>
          <key>CFBundleDisplayName</key>
          <string>OxiCloud Desktop</string>
          <key>CFBundlePackageType</key>
          <string>APPL</string>
          <key>CFBundleVersion</key>
          <string>1.0.0</string>
          <key>CFBundleShortVersionString</key>
          <string>1.0.0</string>
          <key>NSHighResolutionCapable</key>
          <true/>
        </dict>
        </plist>
        EOF
        
        # Create a minimal icon
        echo "Creating a minimal icon file"
        touch OxiCloud.app/Contents/Resources/AppIcon.icns
        
        # Create ZIP archive (primary distribution method)
        echo "Creating ZIP archive of the app bundle"
        zip -r OxiCloud-Desktop-macOS.zip OxiCloud.app
        
        # Create DMG if possible, with better error handling
        echo "Attempting to create DMG"
        if ! hdiutil create -volname "OxiCloud Desktop" -srcfolder OxiCloud.app -ov -format UDZO OxiCloud-Desktop-macOS.dmg 2>/dev/null; then
          echo "DMG creation failed, using ZIP as fallback"
          cp OxiCloud-Desktop-macOS.zip OxiCloud-Desktop-macOS.dmg
        else
          echo "DMG created successfully"
        fi
      
    - name: Upload macOS build
      uses: actions/upload-artifact@v4
      with:
        name: oxicloud-desktop-macos
        path: |
          OxiCloud-Desktop-macOS.dmg
          OxiCloud-Desktop-macOS.zip
        
    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          OxiCloud-Desktop-macOS.dmg
          OxiCloud-Desktop-macOS.zip

  upload-release-assets:
    needs: [build-linux, build-windows, build-macos]
    runs-on: ubuntu-latest
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      
    - name: Get release tag
      id: get_release
      run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      
    - name: Generate SHA256 checksums
      run: |
        echo "Generating checksums for all artifacts"
        find . -type f -name "*.zip" -o -name "*.tar.gz" -o -name "*.dmg" -o -name "*.msi" -o -name "*.deb" | sort | xargs sha256sum > SHA256SUMS.txt
        cat SHA256SUMS.txt
      
    - name: Upload checksums to release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: SHA256SUMS.txt