name: Release Build

on:
  release:
    types: [created]

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libssl-dev pkg-config libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev
    
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
        
    - name: Build
      run: cargo build --release
      
    - name: Create tarball
      run: |
        mkdir -p OxiCloud-Linux
        cp target/release/oxicloud-desktop OxiCloud-Linux/
        cp README.md OxiCloud-Linux/
        cp LICENSE OxiCloud-Linux/
        tar -czvf OxiCloud-Desktop-Linux-x86_64.tar.gz OxiCloud-Linux
      
    - name: Upload Linux build
      uses: actions/upload-artifact@v4
      with:
        name: oxicloud-desktop-linux
        path: OxiCloud-Desktop-Linux-x86_64.tar.gz
        
    - name: Create DEB package
      run: |
        sudo apt-get install -y cargo-deb
        cargo deb
        cp target/debian/*.deb OxiCloud-Desktop-Linux.deb
        
    - name: Upload DEB package
      uses: actions/upload-artifact@v4
      with:
        name: oxicloud-desktop-deb
        path: OxiCloud-Desktop-Linux.deb
        
    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          OxiCloud-Desktop-Linux-x86_64.tar.gz
          OxiCloud-Desktop-Linux.deb

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
        
    - name: Install wix
      run: cargo install cargo-wix
        
    - name: Build
      run: cargo build --release
      
    - name: Create zip
      run: |
        New-Item -ItemType Directory -Path OxiCloud-Windows
        Copy-Item target\release\oxicloud-desktop.exe OxiCloud-Windows\
        Copy-Item README.md OxiCloud-Windows\
        Copy-Item LICENSE OxiCloud-Windows\
        Compress-Archive -Path OxiCloud-Windows\* -DestinationPath OxiCloud-Desktop-Windows-x86_64.zip
      shell: pwsh
      
    - name: Create MSI installer
      run: cargo wix
      
    - name: Upload Windows build
      uses: actions/upload-artifact@v4
      with:
        name: oxicloud-desktop-windows
        path: |
          OxiCloud-Desktop-Windows-x86_64.zip
          target\wix\*.msi
        
    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          OxiCloud-Desktop-Windows-x86_64.zip
          target\wix\*.msi

  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Rust
      uses: actions-rs/toolchain@v1
      with:
        profile: minimal
        toolchain: stable
        override: true
        
    - name: Build
      run: cargo build --release
      
    - name: Create app bundle
      run: |
        mkdir -p OxiCloud.app/Contents/MacOS
        mkdir -p OxiCloud.app/Contents/Resources
        cp target/release/oxicloud-desktop OxiCloud.app/Contents/MacOS/
        
        cat > OxiCloud.app/Contents/Info.plist << EOF
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
          <key>CFBundleExecutable</key>
          <string>oxicloud-desktop</string>
          <key>CFBundleIdentifier</key>
          <string>com.oxicloud.desktop</string>
          <key>CFBundleName</key>
          <string>OxiCloud Desktop</string>
          <key>CFBundleVersion</key>
          <string>1.0.0</string>
          <key>CFBundleShortVersionString</key>
          <string>1.0.0</string>
          <key>CFBundleIconFile</key>
          <string>AppIcon</string>
        </dict>
        </plist>
        EOF
        
        # Create DMG
        hdiutil create -volname "OxiCloud Desktop" -srcfolder OxiCloud.app -ov -format UDZO OxiCloud-Desktop-macOS.dmg
      
    - name: Upload macOS build
      uses: actions/upload-artifact@v4
      with:
        name: oxicloud-desktop-macos
        path: OxiCloud-Desktop-macOS.dmg
        
    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        files: OxiCloud-Desktop-macOS.dmg

  upload-release-assets:
    needs: [build-linux, build-windows, build-macos]
    runs-on: ubuntu-latest
    steps:
    - name: Download all artifacts
      uses: actions/download-artifact@v4
      
    - name: Get release tag
      id: get_release
      run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      
    - name: Generate SHA256 checksums
      run: |
        find . -type f -name "*.zip" -o -name "*.tar.gz" -o -name "*.dmg" -o -name "*.msi" -o -name "*.deb" | sort | xargs sha256sum > SHA256SUMS.txt
      
    - name: Upload checksums to release
      uses: softprops/action-gh-release@v1
      with:
        files: SHA256SUMS.txt