name: Windows Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.29.1'
        channel: 'stable'
    
    - name: Install dependencies
      run: flutter pub get
    
    - name: Debug directory structure
      run: |
        echo "Current directory:"
        pwd
        echo "Listing root directory:"
        dir
        echo "Listing build directory (if exists):"
        dir build -ErrorAction SilentlyContinue
    
    - name: Build Windows
      run: flutter build windows --verbose
    
    - name: Debug build output
      run: |
        echo "Listing build directory after build:"
        dir build -ErrorAction SilentlyContinue
        echo "Listing windows directory (if exists):"
        dir build\windows -ErrorAction SilentlyContinue
        echo "Listing runner directory (if exists):"
        dir build\windows\runner -ErrorAction SilentlyContinue
    
    - name: Upload Windows Artifact
      uses: actions/upload-artifact@v4
      with:
        name: windows-build
        path: build\windows\runner\Release\
        if-no-files-found: error 